// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :execrows
INSERT INTO accounts(id, name, account_id, email, plan, enabled, status, credential, expires_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, 1, ?6, ?7, ?8, ?9, ?10)
ON CONFLICT(account_id) DO NOTHING
`

type CreateAccountParams struct {
	ID         string
	Name       string
	AccountID  string
	Email      string
	Plan       string
	Status     string
	Credential []byte
	ExpiresAt  int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.AccountID,
		arg.Email,
		arg.Plan,
		arg.Status,
		arg.Credential,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = ?1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, account_id, email, "plan", enabled, status, credential, expires_at, created_at, updated_at FROM accounts WHERE id = ?1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.Email,
		&i.Plan,
		&i.Enabled,
		&i.Status,
		&i.Credential,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, email, plan, enabled, status, expires_at, created_at, updated_at
FROM accounts ORDER BY created_at DESC, id DESC LIMIT 100
`

type ListAccountsRow struct {
	ID        string
	Name      string
	Email     string
	Plan      string
	Enabled   bool
	Status    string
	ExpiresAt int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Plan,
			&i.Enabled,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountEnabled = `-- name: SetAccountEnabled :exec
UPDATE accounts SET enabled = ?1, updated_at = ?2 WHERE id = ?3
`

type SetAccountEnabledParams struct {
	Enabled   bool
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetAccountEnabled(ctx context.Context, arg SetAccountEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setAccountEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE accounts SET status = ?1, updated_at = ?2 WHERE id = ?3
`

type SetAccountStatusParams struct {
	Status    string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAccountStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateAccountCredential = `-- name: UpdateAccountCredential :exec
UPDATE accounts SET credential = ?1, email = ?2, plan = ?3, status = ?4, expires_at = ?5, updated_at = ?6
WHERE id = ?7
`

type UpdateAccountCredentialParams struct {
	Credential []byte
	Email      string
	Plan       string
	Status     string
	ExpiresAt  int64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) UpdateAccountCredential(ctx context.Context, arg UpdateAccountCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountCredential,
		arg.Credential,
		arg.Email,
		arg.Plan,
		arg.Status,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
