// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
)

const getHourlyCoverage = `-- name: GetHourlyCoverage :one
SELECT started_at FROM usage_hourly_coverage WHERE id=1
`

func (q *Queries) GetHourlyCoverage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHourlyCoverage)
	var started_at int64
	err := row.Scan(&started_at)
	return started_at, err
}

const listHourlyActivity = `-- name: ListHourlyActivity :many
SELECT CAST((CAST(strftime('%w',h.hour,'unixepoch') AS INTEGER)+6)%7 AS INTEGER) AS weekday,
CAST(strftime('%H',h.hour,'unixepoch') AS INTEGER) AS hour_of_day,
CAST(SUM(h.requests) AS INTEGER) AS requests,
CAST(SUM(h.input_tokens) AS INTEGER) AS input_tokens,
CAST(SUM(h.output_tokens) AS INTEGER) AS output_tokens,
CAST(SUM(h.input_reported) AS INTEGER) AS input_reported,
CAST(SUM(h.output_reported) AS INTEGER) AS output_reported
FROM usage_hourly h
WHERE h.hour>=?1 AND h.hour<?2 AND (h.user_id=?3 OR ?3=0)
GROUP BY 1,2 ORDER BY 1,2 LIMIT 168
`

type ListHourlyActivityParams struct {
	FromHour int64
	ToHour   int64
	UserID   int64
}

type ListHourlyActivityRow struct {
	Weekday        int64
	HourOfDay      int64
	Requests       int64
	InputTokens    int64
	OutputTokens   int64
	InputReported  int64
	OutputReported int64
}

func (q *Queries) ListHourlyActivity(ctx context.Context, arg ListHourlyActivityParams) ([]ListHourlyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listHourlyActivity, arg.FromHour, arg.ToHour, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHourlyActivityRow{}
	for rows.Next() {
		var i ListHourlyActivityRow
		if err := rows.Scan(
			&i.Weekday,
			&i.HourOfDay,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.InputReported,
			&i.OutputReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHourlyUsage = `-- name: PruneHourlyUsage :exec
DELETE FROM usage_hourly WHERE hour<?1
`

func (q *Queries) PruneHourlyUsage(ctx context.Context, beforeHour int64) error {
	_, err := q.db.ExecContext(ctx, pruneHourlyUsage, beforeHour)
	return err
}

const recordHourlyUsage = `-- name: RecordHourlyUsage :exec
INSERT INTO usage_hourly(hour,user_id,requests,input_tokens,output_tokens,input_reported,output_reported)
VALUES(?1,?2,?3,?4,?5,?6,?7)
ON CONFLICT(hour,user_id) DO UPDATE SET
requests=usage_hourly.requests+excluded.requests,
input_tokens=usage_hourly.input_tokens+excluded.input_tokens,
output_tokens=usage_hourly.output_tokens+excluded.output_tokens,
input_reported=usage_hourly.input_reported+excluded.input_reported,
output_reported=usage_hourly.output_reported+excluded.output_reported
`

type RecordHourlyUsageParams struct {
	Hour           int64
	UserID         int64
	Requests       int64
	InputTokens    int64
	OutputTokens   int64
	InputReported  int64
	OutputReported int64
}

func (q *Queries) RecordHourlyUsage(ctx context.Context, arg RecordHourlyUsageParams) error {
	_, err := q.db.ExecContext(ctx, recordHourlyUsage,
		arg.Hour,
		arg.UserID,
		arg.Requests,
		arg.InputTokens,
		arg.OutputTokens,
		arg.InputReported,
		arg.OutputReported,
	)
	return err
}
