// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
)

const clearAlertStates = `-- name: ClearAlertStates :exec
DELETE FROM alert_states WHERE tenant_id=?1
`

func (q *Queries) ClearAlertStates(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, clearAlertStates, tenantID)
	return err
}

const countWebhookSecrets = `-- name: CountWebhookSecrets :one
SELECT COUNT(*) FROM tenants WHERE json_extract(alert_config,'$.endpoint') IS NOT NULL
`

func (q *Queries) CountWebhookSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failAlertDelivery = `-- name: FailAlertDelivery :exec
UPDATE alert_states SET delivery_failed=1 WHERE tenant_id=?1 AND event_id=?2
`

type FailAlertDeliveryParams struct {
	TenantID int64
	EventID  string
}

func (q *Queries) FailAlertDelivery(ctx context.Context, arg FailAlertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, failAlertDelivery, arg.TenantID, arg.EventID)
	return err
}

const finishAlertDelivery = `-- name: FinishAlertDelivery :exec
UPDATE alert_states SET delivered_active=active,delivered_at=?1,attempts=0,retry_at=0,delivery_failed=0
WHERE tenant_id=?2 AND event_id=?3
`

type FinishAlertDeliveryParams struct {
	Now      int64
	TenantID int64
	EventID  string
}

func (q *Queries) FinishAlertDelivery(ctx context.Context, arg FinishAlertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, finishAlertDelivery, arg.Now, arg.TenantID, arg.EventID)
	return err
}

const getAlertConfig = `-- name: GetAlertConfig :one
SELECT alert_config FROM tenants WHERE id=?1 AND status='active'
`

func (q *Queries) GetAlertConfig(ctx context.Context, tenantID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getAlertConfig, tenantID)
	var alert_config string
	err := row.Scan(&alert_config)
	return alert_config, err
}

const listAlertConfigs = `-- name: ListAlertConfigs :many
SELECT id,alert_config FROM tenants WHERE alert_config<>'{}' ORDER BY id
`

type ListAlertConfigsRow struct {
	ID          int64
	AlertConfig string
}

func (q *Queries) ListAlertConfigs(ctx context.Context) ([]ListAlertConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertConfigsRow{}
	for rows.Next() {
		var i ListAlertConfigsRow
		if err := rows.Scan(&i.ID, &i.AlertConfig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertSignals = `-- name: ListAlertSignals :many
SELECT 'account_reauthorization' AS kind,a.id AS subject FROM accounts a
WHERE a.tenant_id=?1 AND a.enabled=1 AND a.provider IN ('codex','claude','antigravity') AND a.status='reauth_required'
UNION ALL
SELECT 'pool_unavailable',CAST(g.id AS TEXT) FROM account_groups g
WHERE g.tenant_id=?1 AND g.enabled=1 AND NOT EXISTS(
 SELECT 1 FROM group_accounts ga JOIN accounts a ON a.id=ga.account_id
 LEFT JOIN account_runtime r ON r.account_id=a.id
 WHERE ga.group_id=g.id AND a.enabled=1 AND a.provider IN ('codex','claude','antigravity') AND a.status='ready'
 AND COALESCE(r.cooldown_until,0)=0
)
UNION ALL
SELECT 'request_failures','workspace' FROM request_records r JOIN account_groups g ON g.id=r.group_id
WHERE g.tenant_id=?1
AND r.started_at+r.duration_ms/1000>=?2
AND r.started_at+r.duration_ms/1000<=?3
AND r.outcome IN ('success','error','incomplete')
GROUP BY g.tenant_id
HAVING COUNT(*)>=5 AND SUM(CASE WHEN r.outcome IN ('error','incomplete') THEN 1 ELSE 0 END)*2>=COUNT(*)
`

type ListAlertSignalsParams struct {
	TenantID int64
	Since    int64
	Now      int64
}

type ListAlertSignalsRow struct {
	Kind    string
	Subject string
}

func (q *Queries) ListAlertSignals(ctx context.Context, arg ListAlertSignalsParams) ([]ListAlertSignalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertSignals, arg.TenantID, arg.Since, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertSignalsRow{}
	for rows.Next() {
		var i ListAlertSignalsRow
		if err := rows.Scan(&i.Kind, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertStates = `-- name: ListAlertStates :many
SELECT tenant_id, kind, subject, active, delivered_active, event_id, changed_at, attempts, retry_at, delivered_at, delivery_failed FROM alert_states WHERE tenant_id=?1 ORDER BY retry_at,changed_at,kind,subject
`

func (q *Queries) ListAlertStates(ctx context.Context, tenantID int64) ([]AlertState, error) {
	rows, err := q.db.QueryContext(ctx, listAlertStates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertState{}
	for rows.Next() {
		var i AlertState
		if err := rows.Scan(
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.Active,
			&i.DeliveredActive,
			&i.EventID,
			&i.ChangedAt,
			&i.Attempts,
			&i.RetryAt,
			&i.DeliveredAt,
			&i.DeliveryFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAlertConfig = `-- name: SaveAlertConfig :execrows
UPDATE tenants SET alert_config=?1 WHERE id=?2 AND status='active'
`

type SaveAlertConfigParams struct {
	Config   string
	TenantID int64
}

func (q *Queries) SaveAlertConfig(ctx context.Context, arg SaveAlertConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAlertConfig, arg.Config, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveAlertState = `-- name: SaveAlertState :exec
INSERT INTO alert_states(tenant_id,kind,subject,active,delivered_active,event_id,changed_at,attempts,retry_at,delivered_at,delivery_failed)
VALUES(?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(tenant_id,kind,subject) DO UPDATE SET active=excluded.active,delivered_active=excluded.delivered_active,
event_id=excluded.event_id,changed_at=excluded.changed_at,attempts=excluded.attempts,retry_at=excluded.retry_at,
delivered_at=excluded.delivered_at,delivery_failed=excluded.delivery_failed
`

type SaveAlertStateParams struct {
	TenantID        int64
	Kind            string
	Subject         string
	Active          int64
	DeliveredActive int64
	EventID         string
	ChangedAt       int64
	Attempts        int64
	RetryAt         int64
	DeliveredAt     int64
	DeliveryFailed  int64
}

func (q *Queries) SaveAlertState(ctx context.Context, arg SaveAlertStateParams) error {
	_, err := q.db.ExecContext(ctx, saveAlertState,
		arg.TenantID,
		arg.Kind,
		arg.Subject,
		arg.Active,
		arg.DeliveredActive,
		arg.EventID,
		arg.ChangedAt,
		arg.Attempts,
		arg.RetryAt,
		arg.DeliveredAt,
		arg.DeliveryFailed,
	)
	return err
}
