// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocations.sql

package db

import (
	"context"
)

const accountHasAllocation = `-- name: AccountHasAllocation :one
SELECT EXISTS(SELECT 1 FROM group_accounts ga JOIN allocation_schemes s ON s.group_id=ga.group_id WHERE ga.account_id=?)
`

func (q *Queries) AccountHasAllocation(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountHasAllocation, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const allocationMemberExposure = `-- name: AllocationMemberExposure :one
SELECT CAST(COALESCE(SUM(CASE WHEN state='active' THEN 1 ELSE 0 END),0) AS INTEGER) AS active,
CAST(COALESCE(SUM(CASE WHEN state='pending' THEN 1 ELSE 0 END),0) AS INTEGER) AS pending
FROM allocation_entries WHERE scheme_id=?1 AND user_id=?2
AND started_at>=?3 AND started_at<?4
AND mode=?5 AND state IN ('active','pending')
`

type AllocationMemberExposureParams struct {
	SchemeID    int64
	UserID      int64
	StartedFrom int64
	StartedTo   int64
	Mode        string
}

type AllocationMemberExposureRow struct {
	Active  int64
	Pending int64
}

func (q *Queries) AllocationMemberExposure(ctx context.Context, arg AllocationMemberExposureParams) (AllocationMemberExposureRow, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberExposure,
		arg.SchemeID,
		arg.UserID,
		arg.StartedFrom,
		arg.StartedTo,
		arg.Mode,
	)
	var i AllocationMemberExposureRow
	err := row.Scan(&i.Active, &i.Pending)
	return i, err
}

const allocationMemberPending = `-- name: AllocationMemberPending :one
SELECT count(*) FROM allocation_entries WHERE scheme_id=? AND user_id=? AND state='pending'
`

type AllocationMemberPendingParams struct {
	SchemeID int64
	UserID   int64
}

func (q *Queries) AllocationMemberPending(ctx context.Context, arg AllocationMemberPendingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberPending, arg.SchemeID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allocationMemberUsage = `-- name: AllocationMemberUsage :one
SELECT CAST(COALESCE(sum(cost),0) AS INTEGER) AS used,CAST(COALESCE(sum(input_tokens+output_tokens),0) AS INTEGER) AS tokens
FROM allocation_entries WHERE scheme_id=?1 AND user_id=?2
AND started_at>=?3 AND started_at<?4 AND mode=?5
`

type AllocationMemberUsageParams struct {
	SchemeID    int64
	UserID      int64
	StartedFrom int64
	StartedTo   int64
	Mode        string
}

type AllocationMemberUsageRow struct {
	Used   int64
	Tokens int64
}

// A time-zone change reassigns existing requests by their start instant, regardless of their stored original window.
func (q *Queries) AllocationMemberUsage(ctx context.Context, arg AllocationMemberUsageParams) (AllocationMemberUsageRow, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberUsage,
		arg.SchemeID,
		arg.UserID,
		arg.StartedFrom,
		arg.StartedTo,
		arg.Mode,
	)
	var i AllocationMemberUsageRow
	err := row.Scan(&i.Used, &i.Tokens)
	return i, err
}

const allocationPoolAccounts = `-- name: AllocationPoolAccounts :many
SELECT a.id,a.provider,a.models_revision,(SELECT count(*) FROM group_accounts other WHERE other.account_id=a.id AND other.group_id<>ga.group_id) AS shared
FROM group_accounts ga JOIN accounts a ON a.id=ga.account_id WHERE ga.group_id=? ORDER BY a.id
`

type AllocationPoolAccountsRow struct {
	ID             string
	Provider       string
	ModelsRevision int64
	Shared         int64
}

func (q *Queries) AllocationPoolAccounts(ctx context.Context, groupID int64) ([]AllocationPoolAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, allocationPoolAccounts, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationPoolAccountsRow{}
	for rows.Next() {
		var i AllocationPoolAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelsRevision,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const beginAllocationEntry = `-- name: BeginAllocationEntry :exec
INSERT INTO allocation_entries(request_id,scheme_id,revision_id,user_id,account_id,model,mode,window_start,reset_at,started_at,state)
VALUES(?,?,?,?,?,?,?,?,?,?,'active')
`

type BeginAllocationEntryParams struct {
	RequestID   string
	SchemeID    int64
	RevisionID  int64
	UserID      int64
	AccountID   string
	Model       string
	Mode        string
	WindowStart int64
	ResetAt     int64
	StartedAt   int64
}

func (q *Queries) BeginAllocationEntry(ctx context.Context, arg BeginAllocationEntryParams) error {
	_, err := q.db.ExecContext(ctx, beginAllocationEntry,
		arg.RequestID,
		arg.SchemeID,
		arg.RevisionID,
		arg.UserID,
		arg.AccountID,
		arg.Model,
		arg.Mode,
		arg.WindowStart,
		arg.ResetAt,
		arg.StartedAt,
	)
	return err
}

const bindKeyAllocation = `-- name: BindKeyAllocation :exec
INSERT INTO allocation_keys(key_id,scheme_id) VALUES(?,?)
`

type BindKeyAllocationParams struct {
	KeyID    int64
	SchemeID int64
}

func (q *Queries) BindKeyAllocation(ctx context.Context, arg BindKeyAllocationParams) error {
	_, err := q.db.ExecContext(ctx, bindKeyAllocation, arg.KeyID, arg.SchemeID)
	return err
}

const canUseAllocation = `-- name: CanUseAllocation :one
SELECT EXISTS(SELECT 1 FROM allocation_schemes s
JOIN effective_group_access access ON access.group_id=s.group_id
WHERE s.id=? AND access.user_id=? AND s.enabled=1)
`

type CanUseAllocationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) CanUseAllocation(ctx context.Context, arg CanUseAllocationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canUseAllocation, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAllocationScheme = `-- name: CreateAllocationScheme :execlastid
INSERT INTO allocation_schemes(name,group_id,enabled,created_at) VALUES(?,?,?,?)
`

type CreateAllocationSchemeParams struct {
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
}

func (q *Queries) CreateAllocationScheme(ctx context.Context, arg CreateAllocationSchemeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAllocationScheme,
		arg.Name,
		arg.GroupID,
		arg.Enabled,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const currentAllocationRevision = `-- name: CurrentAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE scheme_id=? AND effective_at<=? ORDER BY effective_at DESC LIMIT 1
`

type CurrentAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) CurrentAllocationRevision(ctx context.Context, arg CurrentAllocationRevisionParams) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, currentAllocationRevision, arg.SchemeID, arg.EffectiveAt)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const deleteNextAllocationRevisions = `-- name: DeleteNextAllocationRevisions :exec
DELETE FROM allocation_revisions WHERE scheme_id=? AND effective_at>?
`

type DeleteNextAllocationRevisionsParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) DeleteNextAllocationRevisions(ctx context.Context, arg DeleteNextAllocationRevisionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteNextAllocationRevisions, arg.SchemeID, arg.EffectiveAt)
	return err
}

const finishAllocationEntry = `-- name: FinishAllocationEntry :exec
UPDATE allocation_entries SET finished_at=?,state=?,input_tokens=?,output_tokens=?,cached_tokens=?,cost=?,manual=? WHERE request_id=?
`

type FinishAllocationEntryParams struct {
	FinishedAt   int64
	State        string
	InputTokens  int64
	OutputTokens int64
	CachedTokens int64
	Cost         int64
	Manual       int64
	RequestID    string
}

func (q *Queries) FinishAllocationEntry(ctx context.Context, arg FinishAllocationEntryParams) error {
	_, err := q.db.ExecContext(ctx, finishAllocationEntry,
		arg.FinishedAt,
		arg.State,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Cost,
		arg.Manual,
		arg.RequestID,
	)
	return err
}

const getAllocationEntry = `-- name: GetAllocationEntry :one
SELECT request_id, scheme_id, revision_id, user_id, account_id, model, mode, window_start, reset_at, started_at, finished_at, state, input_tokens, output_tokens, cached_tokens, cost, manual FROM allocation_entries WHERE request_id=?
`

func (q *Queries) GetAllocationEntry(ctx context.Context, requestID string) (AllocationEntry, error) {
	row := q.db.QueryRowContext(ctx, getAllocationEntry, requestID)
	var i AllocationEntry
	err := row.Scan(
		&i.RequestID,
		&i.SchemeID,
		&i.RevisionID,
		&i.UserID,
		&i.AccountID,
		&i.Model,
		&i.Mode,
		&i.WindowStart,
		&i.ResetAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.Cost,
		&i.Manual,
	)
	return i, err
}

const getAllocationRevision = `-- name: GetAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE id=?
`

func (q *Queries) GetAllocationRevision(ctx context.Context, id int64) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, getAllocationRevision, id)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const getAllocationScheme = `-- name: GetAllocationScheme :one
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE s.id=?
`

type GetAllocationSchemeRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) GetAllocationScheme(ctx context.Context, id int64) (GetAllocationSchemeRow, error) {
	row := q.db.QueryRowContext(ctx, getAllocationScheme, id)
	var i GetAllocationSchemeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Enabled,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const getKeyAllocation = `-- name: GetKeyAllocation :one
SELECT scheme_id FROM allocation_keys WHERE key_id=?
`

func (q *Queries) GetKeyAllocation(ctx context.Context, keyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getKeyAllocation, keyID)
	var scheme_id int64
	err := row.Scan(&scheme_id)
	return scheme_id, err
}

const getPoolAllocation = `-- name: GetPoolAllocation :one
SELECT id FROM allocation_schemes WHERE group_id=?
`

func (q *Queries) GetPoolAllocation(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPoolAllocation, groupID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTenantAllocationScheme = `-- name: GetTenantAllocationScheme :one
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE s.id=?1 AND g.tenant_id=?2
`

type GetTenantAllocationSchemeParams struct {
	ID       int64
	TenantID int64
}

type GetTenantAllocationSchemeRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) GetTenantAllocationScheme(ctx context.Context, arg GetTenantAllocationSchemeParams) (GetTenantAllocationSchemeRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantAllocationScheme, arg.ID, arg.TenantID)
	var i GetTenantAllocationSchemeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Enabled,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const listAllocationPending = `-- name: ListAllocationPending :many
SELECT request_id, scheme_id, revision_id, user_id, account_id, model, mode, window_start, reset_at, started_at, finished_at, state, input_tokens, output_tokens, cached_tokens, cost, manual FROM allocation_entries WHERE scheme_id=?1 AND (?2=0 OR user_id=?2) AND state='pending' ORDER BY started_at DESC,request_id DESC LIMIT 256
`

type ListAllocationPendingParams struct {
	SchemeID int64
	UserID   interface{}
}

func (q *Queries) ListAllocationPending(ctx context.Context, arg ListAllocationPendingParams) ([]AllocationEntry, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationPending, arg.SchemeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationEntry{}
	for rows.Next() {
		var i AllocationEntry
		if err := rows.Scan(
			&i.RequestID,
			&i.SchemeID,
			&i.RevisionID,
			&i.UserID,
			&i.AccountID,
			&i.Model,
			&i.Mode,
			&i.WindowStart,
			&i.ResetAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.State,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.Cost,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationSchemes = `-- name: ListAllocationSchemes :many
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE g.tenant_id=?1 ORDER BY s.id
`

type ListAllocationSchemesRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) ListAllocationSchemes(ctx context.Context, tenantID int64) ([]ListAllocationSchemesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationSchemes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllocationSchemesRow{}
	for rows.Next() {
		var i ListAllocationSchemesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Enabled,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAllocationRevision = `-- name: NextAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE scheme_id=? AND effective_at>? ORDER BY effective_at LIMIT 1
`

type NextAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) NextAllocationRevision(ctx context.Context, arg NextAllocationRevisionParams) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, nextAllocationRevision, arg.SchemeID, arg.EffectiveAt)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const pruneAllocations = `-- name: PruneAllocations :exec
DELETE FROM allocation_entries WHERE state='settled' AND reset_at<?1
`

func (q *Queries) PruneAllocations(ctx context.Context, before int64) error {
	_, err := q.db.ExecContext(ctx, pruneAllocations, before)
	return err
}

const recoverAllocationEntries = `-- name: RecoverAllocationEntries :exec
UPDATE allocation_entries SET state='pending' WHERE state='active' AND EXISTS(
SELECT 1 FROM allocation_schemes s JOIN account_groups g ON g.id=s.group_id
WHERE s.id=allocation_entries.scheme_id AND g.tenant_id=?1)
`

func (q *Queries) RecoverAllocationEntries(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, recoverAllocationEntries, tenantID)
	return err
}

const saveAllocationRevision = `-- name: SaveAllocationRevision :execlastid
INSERT INTO allocation_revisions(scheme_id,effective_at,config) VALUES(?,?,?)
`

type SaveAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
	Config      string
}

func (q *Queries) SaveAllocationRevision(ctx context.Context, arg SaveAllocationRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAllocationRevision, arg.SchemeID, arg.EffectiveAt, arg.Config)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const updateAllocationScheme = `-- name: UpdateAllocationScheme :exec
UPDATE allocation_schemes SET name=?,enabled=? WHERE id=?
`

type UpdateAllocationSchemeParams struct {
	Name    string
	Enabled int64
	ID      int64
}

func (q *Queries) UpdateAllocationScheme(ctx context.Context, arg UpdateAllocationSchemeParams) error {
	_, err := q.db.ExecContext(ctx, updateAllocationScheme, arg.Name, arg.Enabled, arg.ID)
	return err
}
