// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocations.sql

package db

import (
	"context"
)

const accountHasAllocation = `-- name: AccountHasAllocation :one
SELECT EXISTS(SELECT 1 FROM group_accounts ga JOIN allocation_schemes s ON s.group_id=ga.group_id WHERE ga.account_id=?)
`

func (q *Queries) AccountHasAllocation(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountHasAllocation, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const addAllocationWindowMember = `-- name: AddAllocationWindowMember :exec
INSERT INTO allocation_window_members(window_id,user_id,allowance) VALUES(?,?,?)
`

type AddAllocationWindowMemberParams struct {
	WindowID  int64
	UserID    int64
	Allowance int64
}

func (q *Queries) AddAllocationWindowMember(ctx context.Context, arg AddAllocationWindowMemberParams) error {
	_, err := q.db.ExecContext(ctx, addAllocationWindowMember, arg.WindowID, arg.UserID, arg.Allowance)
	return err
}

const advanceManualAllocationWindow = `-- name: AdvanceManualAllocationWindow :exec
UPDATE allocation_windows SET observed_points=observed_points+? WHERE id=?
`

type AdvanceManualAllocationWindowParams struct {
	ObservedPoints int64
	ID             int64
}

func (q *Queries) AdvanceManualAllocationWindow(ctx context.Context, arg AdvanceManualAllocationWindowParams) error {
	_, err := q.db.ExecContext(ctx, advanceManualAllocationWindow, arg.ObservedPoints, arg.ID)
	return err
}

const allocationAccountAwaiting = `-- name: AllocationAccountAwaiting :one
SELECT count(*) AS count, CAST(COALESCE(min(finished_at),0) AS INTEGER) AS oldest
FROM allocation_entries WHERE scheme_id=? AND account_id=? AND state='observed'
`

type AllocationAccountAwaitingParams struct {
	SchemeID  int64
	AccountID string
}

type AllocationAccountAwaitingRow struct {
	Count  int64
	Oldest int64
}

func (q *Queries) AllocationAccountAwaiting(ctx context.Context, arg AllocationAccountAwaitingParams) (AllocationAccountAwaitingRow, error) {
	row := q.db.QueryRowContext(ctx, allocationAccountAwaiting, arg.SchemeID, arg.AccountID)
	var i AllocationAccountAwaitingRow
	err := row.Scan(&i.Count, &i.Oldest)
	return i, err
}

const allocationAccountObserved = `-- name: AllocationAccountObserved :one
SELECT count(*) FROM allocation_entries WHERE scheme_id=? AND account_id=? AND state IN ('active','observed')
`

type AllocationAccountObservedParams struct {
	SchemeID  int64
	AccountID string
}

func (q *Queries) AllocationAccountObserved(ctx context.Context, arg AllocationAccountObservedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationAccountObserved, arg.SchemeID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allocationAccountUnfinished = `-- name: AllocationAccountUnfinished :one
SELECT count(*) FROM allocation_entries WHERE account_id=? AND state IN ('active','pending')
`

func (q *Queries) AllocationAccountUnfinished(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationAccountUnfinished, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allocationMemberPending = `-- name: AllocationMemberPending :one
SELECT count(*) FROM allocation_entries WHERE scheme_id=? AND user_id=? AND state='pending'
`

type AllocationMemberPendingParams struct {
	SchemeID int64
	UserID   int64
}

func (q *Queries) AllocationMemberPending(ctx context.Context, arg AllocationMemberPendingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberPending, arg.SchemeID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allocationMemberUnresolved = `-- name: AllocationMemberUnresolved :one
SELECT count(*) FROM allocation_entries e WHERE e.scheme_id=? AND e.user_id=? AND (e.state='pending'
OR (e.state='observed' AND EXISTS(SELECT 1 FROM allocation_debits d JOIN allocation_windows w ON w.id=d.window_id
WHERE d.request_id=e.request_id AND d.reconciled=0 AND w.reset_at<=?)))
`

type AllocationMemberUnresolvedParams struct {
	SchemeID int64
	UserID   int64
	ResetAt  int64
}

func (q *Queries) AllocationMemberUnresolved(ctx context.Context, arg AllocationMemberUnresolvedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberUnresolved, arg.SchemeID, arg.UserID, arg.ResetAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const allocationMemberUsage = `-- name: AllocationMemberUsage :one
SELECT CAST(COALESCE(sum(cost),0) AS INTEGER) AS used,CAST(COALESCE(sum(input_tokens+output_tokens),0) AS INTEGER) AS tokens
FROM allocation_entries WHERE scheme_id=? AND user_id=? AND window_start=? AND mode=?
`

type AllocationMemberUsageParams struct {
	SchemeID    int64
	UserID      int64
	WindowStart int64
	Mode        string
}

type AllocationMemberUsageRow struct {
	Used   int64
	Tokens int64
}

func (q *Queries) AllocationMemberUsage(ctx context.Context, arg AllocationMemberUsageParams) (AllocationMemberUsageRow, error) {
	row := q.db.QueryRowContext(ctx, allocationMemberUsage,
		arg.SchemeID,
		arg.UserID,
		arg.WindowStart,
		arg.Mode,
	)
	var i AllocationMemberUsageRow
	err := row.Scan(&i.Used, &i.Tokens)
	return i, err
}

const allocationPoolAccounts = `-- name: AllocationPoolAccounts :many
SELECT a.id,a.provider,a.models_revision,(SELECT count(*) FROM group_accounts other WHERE other.account_id=a.id AND other.group_id<>ga.group_id) AS shared
FROM group_accounts ga JOIN accounts a ON a.id=ga.account_id WHERE ga.group_id=? ORDER BY a.id
`

type AllocationPoolAccountsRow struct {
	ID             string
	Provider       string
	ModelsRevision int64
	Shared         int64
}

func (q *Queries) AllocationPoolAccounts(ctx context.Context, groupID int64) ([]AllocationPoolAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, allocationPoolAccounts, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationPoolAccountsRow{}
	for rows.Next() {
		var i AllocationPoolAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelsRevision,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allocationUnassigned = `-- name: AllocationUnassigned :one
SELECT CAST(COALESCE(sum(unassigned),0) AS INTEGER) FROM allocation_windows WHERE scheme_id=?
`

func (q *Queries) AllocationUnassigned(ctx context.Context, schemeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationUnassigned, schemeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const allocationWindowTokens = `-- name: AllocationWindowTokens :one
SELECT CAST(COALESCE(sum(e.input_tokens+e.output_tokens),0) AS INTEGER) FROM allocation_debits d
JOIN allocation_entries e ON e.request_id=d.request_id WHERE d.window_id=? AND e.user_id=?
`

type AllocationWindowTokensParams struct {
	WindowID int64
	UserID   int64
}

func (q *Queries) AllocationWindowTokens(ctx context.Context, arg AllocationWindowTokensParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, allocationWindowTokens, arg.WindowID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const allocationWindowUsage = `-- name: AllocationWindowUsage :many
SELECT m.user_id,m.allowance,CAST(COALESCE(sum(d.points),0) AS INTEGER) AS used
FROM allocation_window_members m LEFT JOIN allocation_entries e ON e.user_id=m.user_id
LEFT JOIN allocation_debits d ON d.request_id=e.request_id AND d.window_id=m.window_id
WHERE m.window_id=?1 AND (?2=0 OR m.user_id=?2) GROUP BY m.user_id,m.allowance ORDER BY m.user_id
`

type AllocationWindowUsageParams struct {
	WindowID int64
	UserID   interface{}
}

type AllocationWindowUsageRow struct {
	UserID    int64
	Allowance int64
	Used      int64
}

func (q *Queries) AllocationWindowUsage(ctx context.Context, arg AllocationWindowUsageParams) ([]AllocationWindowUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, allocationWindowUsage, arg.WindowID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationWindowUsageRow{}
	for rows.Next() {
		var i AllocationWindowUsageRow
		if err := rows.Scan(&i.UserID, &i.Allowance, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const beginAllocationDebit = `-- name: BeginAllocationDebit :exec
INSERT INTO allocation_debits(request_id,window_id) VALUES(?,?)
`

type BeginAllocationDebitParams struct {
	RequestID string
	WindowID  int64
}

func (q *Queries) BeginAllocationDebit(ctx context.Context, arg BeginAllocationDebitParams) error {
	_, err := q.db.ExecContext(ctx, beginAllocationDebit, arg.RequestID, arg.WindowID)
	return err
}

const beginAllocationEntry = `-- name: BeginAllocationEntry :exec
INSERT INTO allocation_entries(request_id,scheme_id,revision_id,user_id,account_id,model,mode,window_start,reset_at,started_at,state)
VALUES(?,?,?,?,?,?,?,?,?,?,'active')
`

type BeginAllocationEntryParams struct {
	RequestID   string
	SchemeID    int64
	RevisionID  int64
	UserID      int64
	AccountID   string
	Model       string
	Mode        string
	WindowStart int64
	ResetAt     int64
	StartedAt   int64
}

func (q *Queries) BeginAllocationEntry(ctx context.Context, arg BeginAllocationEntryParams) error {
	_, err := q.db.ExecContext(ctx, beginAllocationEntry,
		arg.RequestID,
		arg.SchemeID,
		arg.RevisionID,
		arg.UserID,
		arg.AccountID,
		arg.Model,
		arg.Mode,
		arg.WindowStart,
		arg.ResetAt,
		arg.StartedAt,
	)
	return err
}

const bindKeyAllocation = `-- name: BindKeyAllocation :exec
INSERT INTO allocation_keys(key_id,scheme_id) VALUES(?,?)
`

type BindKeyAllocationParams struct {
	KeyID    int64
	SchemeID int64
}

func (q *Queries) BindKeyAllocation(ctx context.Context, arg BindKeyAllocationParams) error {
	_, err := q.db.ExecContext(ctx, bindKeyAllocation, arg.KeyID, arg.SchemeID)
	return err
}

const canUseAllocation = `-- name: CanUseAllocation :one
SELECT EXISTS(SELECT 1 FROM allocation_schemes s
JOIN effective_group_access access ON access.group_id=s.group_id
WHERE s.id=? AND access.user_id=? AND s.enabled=1)
`

type CanUseAllocationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) CanUseAllocation(ctx context.Context, arg CanUseAllocationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canUseAllocation, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearAllocationUnassigned = `-- name: ClearAllocationUnassigned :exec
UPDATE allocation_windows SET unassigned=0 WHERE scheme_id=?
`

func (q *Queries) ClearAllocationUnassigned(ctx context.Context, schemeID int64) error {
	_, err := q.db.ExecContext(ctx, clearAllocationUnassigned, schemeID)
	return err
}

const createAllocationScheme = `-- name: CreateAllocationScheme :execlastid
INSERT INTO allocation_schemes(name,group_id,enabled,created_at) VALUES(?,?,?,?)
`

type CreateAllocationSchemeParams struct {
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
}

func (q *Queries) CreateAllocationScheme(ctx context.Context, arg CreateAllocationSchemeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAllocationScheme,
		arg.Name,
		arg.GroupID,
		arg.Enabled,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAllocationWindow = `-- name: CreateAllocationWindow :execlastid
INSERT INTO allocation_windows(scheme_id,account_id,kind,reset_at,account_revision,observed_at,observed_points,baseline_points)
VALUES(?,?,?,?,?,?,?,?)
`

type CreateAllocationWindowParams struct {
	SchemeID        int64
	AccountID       string
	Kind            string
	ResetAt         int64
	AccountRevision int64
	ObservedAt      int64
	ObservedPoints  int64
	BaselinePoints  int64
}

func (q *Queries) CreateAllocationWindow(ctx context.Context, arg CreateAllocationWindowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAllocationWindow,
		arg.SchemeID,
		arg.AccountID,
		arg.Kind,
		arg.ResetAt,
		arg.AccountRevision,
		arg.ObservedAt,
		arg.ObservedPoints,
		arg.BaselinePoints,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const currentAccountAllocationWindows = `-- name: CurrentAccountAllocationWindows :many
SELECT id, scheme_id, account_id, kind, reset_at, account_revision, observed_at, observed_points, baseline_points, unassigned FROM allocation_windows WHERE scheme_id=? AND account_id=? AND reset_at>? ORDER BY kind
`

type CurrentAccountAllocationWindowsParams struct {
	SchemeID  int64
	AccountID string
	ResetAt   int64
}

func (q *Queries) CurrentAccountAllocationWindows(ctx context.Context, arg CurrentAccountAllocationWindowsParams) ([]AllocationWindow, error) {
	rows, err := q.db.QueryContext(ctx, currentAccountAllocationWindows, arg.SchemeID, arg.AccountID, arg.ResetAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationWindow{}
	for rows.Next() {
		var i AllocationWindow
		if err := rows.Scan(
			&i.ID,
			&i.SchemeID,
			&i.AccountID,
			&i.Kind,
			&i.ResetAt,
			&i.AccountRevision,
			&i.ObservedAt,
			&i.ObservedPoints,
			&i.BaselinePoints,
			&i.Unassigned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const currentAllocationRevision = `-- name: CurrentAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE scheme_id=? AND effective_at<=? ORDER BY effective_at DESC LIMIT 1
`

type CurrentAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) CurrentAllocationRevision(ctx context.Context, arg CurrentAllocationRevisionParams) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, currentAllocationRevision, arg.SchemeID, arg.EffectiveAt)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const deleteNextAllocationRevisions = `-- name: DeleteNextAllocationRevisions :exec
DELETE FROM allocation_revisions WHERE scheme_id=? AND effective_at>?
`

type DeleteNextAllocationRevisionsParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) DeleteNextAllocationRevisions(ctx context.Context, arg DeleteNextAllocationRevisionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteNextAllocationRevisions, arg.SchemeID, arg.EffectiveAt)
	return err
}

const findAllocationWindow = `-- name: FindAllocationWindow :one
SELECT id, scheme_id, account_id, kind, reset_at, account_revision, observed_at, observed_points, baseline_points, unassigned FROM allocation_windows WHERE scheme_id=? AND account_id=? AND kind=? AND reset_at=?
`

type FindAllocationWindowParams struct {
	SchemeID  int64
	AccountID string
	Kind      string
	ResetAt   int64
}

func (q *Queries) FindAllocationWindow(ctx context.Context, arg FindAllocationWindowParams) (AllocationWindow, error) {
	row := q.db.QueryRowContext(ctx, findAllocationWindow,
		arg.SchemeID,
		arg.AccountID,
		arg.Kind,
		arg.ResetAt,
	)
	var i AllocationWindow
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.AccountID,
		&i.Kind,
		&i.ResetAt,
		&i.AccountRevision,
		&i.ObservedAt,
		&i.ObservedPoints,
		&i.BaselinePoints,
		&i.Unassigned,
	)
	return i, err
}

const finishAllocationEntry = `-- name: FinishAllocationEntry :exec
UPDATE allocation_entries SET finished_at=?,state=?,input_tokens=?,output_tokens=?,cached_tokens=?,cost=?,manual=? WHERE request_id=?
`

type FinishAllocationEntryParams struct {
	FinishedAt   int64
	State        string
	InputTokens  int64
	OutputTokens int64
	CachedTokens int64
	Cost         int64
	Manual       int64
	RequestID    string
}

func (q *Queries) FinishAllocationEntry(ctx context.Context, arg FinishAllocationEntryParams) error {
	_, err := q.db.ExecContext(ctx, finishAllocationEntry,
		arg.FinishedAt,
		arg.State,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Cost,
		arg.Manual,
		arg.RequestID,
	)
	return err
}

const getAllocationEntry = `-- name: GetAllocationEntry :one
SELECT request_id, scheme_id, revision_id, user_id, account_id, model, mode, window_start, reset_at, started_at, finished_at, state, input_tokens, output_tokens, cached_tokens, cost, manual FROM allocation_entries WHERE request_id=?
`

func (q *Queries) GetAllocationEntry(ctx context.Context, requestID string) (AllocationEntry, error) {
	row := q.db.QueryRowContext(ctx, getAllocationEntry, requestID)
	var i AllocationEntry
	err := row.Scan(
		&i.RequestID,
		&i.SchemeID,
		&i.RevisionID,
		&i.UserID,
		&i.AccountID,
		&i.Model,
		&i.Mode,
		&i.WindowStart,
		&i.ResetAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.Cost,
		&i.Manual,
	)
	return i, err
}

const getAllocationRevision = `-- name: GetAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE id=?
`

func (q *Queries) GetAllocationRevision(ctx context.Context, id int64) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, getAllocationRevision, id)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const getAllocationScheme = `-- name: GetAllocationScheme :one
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE s.id=?
`

type GetAllocationSchemeRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) GetAllocationScheme(ctx context.Context, id int64) (GetAllocationSchemeRow, error) {
	row := q.db.QueryRowContext(ctx, getAllocationScheme, id)
	var i GetAllocationSchemeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Enabled,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const getAllocationWindow = `-- name: GetAllocationWindow :one
SELECT id, scheme_id, account_id, kind, reset_at, account_revision, observed_at, observed_points, baseline_points, unassigned FROM allocation_windows WHERE id=?
`

func (q *Queries) GetAllocationWindow(ctx context.Context, id int64) (AllocationWindow, error) {
	row := q.db.QueryRowContext(ctx, getAllocationWindow, id)
	var i AllocationWindow
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.AccountID,
		&i.Kind,
		&i.ResetAt,
		&i.AccountRevision,
		&i.ObservedAt,
		&i.ObservedPoints,
		&i.BaselinePoints,
		&i.Unassigned,
	)
	return i, err
}

const getKeyAllocation = `-- name: GetKeyAllocation :one
SELECT scheme_id FROM allocation_keys WHERE key_id=?
`

func (q *Queries) GetKeyAllocation(ctx context.Context, keyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getKeyAllocation, keyID)
	var scheme_id int64
	err := row.Scan(&scheme_id)
	return scheme_id, err
}

const getPoolAllocation = `-- name: GetPoolAllocation :one
SELECT id FROM allocation_schemes WHERE group_id=?
`

func (q *Queries) GetPoolAllocation(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPoolAllocation, groupID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRequestAllocationDebits = `-- name: GetRequestAllocationDebits :many
SELECT d.request_id, d.window_id, d.points, d.reconciled,w.kind,w.reset_at,w.account_id FROM allocation_debits d JOIN allocation_windows w ON w.id=d.window_id WHERE request_id=?
`

type GetRequestAllocationDebitsRow struct {
	RequestID  string
	WindowID   int64
	Points     int64
	Reconciled int64
	Kind       string
	ResetAt    int64
	AccountID  string
}

func (q *Queries) GetRequestAllocationDebits(ctx context.Context, requestID string) ([]GetRequestAllocationDebitsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRequestAllocationDebits, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRequestAllocationDebitsRow{}
	for rows.Next() {
		var i GetRequestAllocationDebitsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.WindowID,
			&i.Points,
			&i.Reconciled,
			&i.Kind,
			&i.ResetAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantAllocationScheme = `-- name: GetTenantAllocationScheme :one
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE s.id=?1 AND g.tenant_id=?2
`

type GetTenantAllocationSchemeParams struct {
	ID       int64
	TenantID int64
}

type GetTenantAllocationSchemeRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) GetTenantAllocationScheme(ctx context.Context, arg GetTenantAllocationSchemeParams) (GetTenantAllocationSchemeRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantAllocationScheme, arg.ID, arg.TenantID)
	var i GetTenantAllocationSchemeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Enabled,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const listAllocationDebits = `-- name: ListAllocationDebits :many
SELECT d.request_id, d.window_id, d.points, d.reconciled,e.cost,e.state,e.finished_at,e.started_at,e.user_id FROM allocation_debits d
JOIN allocation_entries e ON e.request_id=d.request_id WHERE window_id=? AND reconciled=0 ORDER BY e.started_at,e.request_id
`

type ListAllocationDebitsRow struct {
	RequestID  string
	WindowID   int64
	Points     int64
	Reconciled int64
	Cost       int64
	State      string
	FinishedAt int64
	StartedAt  int64
	UserID     int64
}

func (q *Queries) ListAllocationDebits(ctx context.Context, windowID int64) ([]ListAllocationDebitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationDebits, windowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllocationDebitsRow{}
	for rows.Next() {
		var i ListAllocationDebitsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.WindowID,
			&i.Points,
			&i.Reconciled,
			&i.Cost,
			&i.State,
			&i.FinishedAt,
			&i.StartedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationPending = `-- name: ListAllocationPending :many
SELECT request_id, scheme_id, revision_id, user_id, account_id, model, mode, window_start, reset_at, started_at, finished_at, state, input_tokens, output_tokens, cached_tokens, cost, manual FROM allocation_entries WHERE scheme_id=?1 AND (?2=0 OR user_id=?2) AND (state='pending' OR state='observed') ORDER BY started_at LIMIT 256
`

type ListAllocationPendingParams struct {
	SchemeID int64
	UserID   interface{}
}

func (q *Queries) ListAllocationPending(ctx context.Context, arg ListAllocationPendingParams) ([]AllocationEntry, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationPending, arg.SchemeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationEntry{}
	for rows.Next() {
		var i AllocationEntry
		if err := rows.Scan(
			&i.RequestID,
			&i.SchemeID,
			&i.RevisionID,
			&i.UserID,
			&i.AccountID,
			&i.Model,
			&i.Mode,
			&i.WindowStart,
			&i.ResetAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.State,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.Cost,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationSchemes = `-- name: ListAllocationSchemes :many
SELECT s.id, s.name, s.group_id, s.enabled, s.created_at,g.name AS group_name FROM allocation_schemes s
JOIN account_groups g ON g.id=s.group_id WHERE g.tenant_id=?1 ORDER BY s.id
`

type ListAllocationSchemesRow struct {
	ID        int64
	Name      string
	GroupID   int64
	Enabled   int64
	CreatedAt int64
	GroupName string
}

func (q *Queries) ListAllocationSchemes(ctx context.Context, tenantID int64) ([]ListAllocationSchemesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationSchemes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllocationSchemesRow{}
	for rows.Next() {
		var i ListAllocationSchemesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Enabled,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationWindows = `-- name: ListAllocationWindows :many
SELECT id, scheme_id, account_id, kind, reset_at, account_revision, observed_at, observed_points, baseline_points, unassigned FROM allocation_windows WHERE scheme_id=? ORDER BY account_id,kind,reset_at DESC
`

func (q *Queries) ListAllocationWindows(ctx context.Context, schemeID int64) ([]AllocationWindow, error) {
	rows, err := q.db.QueryContext(ctx, listAllocationWindows, schemeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationWindow{}
	for rows.Next() {
		var i AllocationWindow
		if err := rows.Scan(
			&i.ID,
			&i.SchemeID,
			&i.AccountID,
			&i.Kind,
			&i.ResetAt,
			&i.AccountRevision,
			&i.ObservedAt,
			&i.ObservedPoints,
			&i.BaselinePoints,
			&i.Unassigned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredAllocationEntries = `-- name: MarkExpiredAllocationEntries :exec
UPDATE allocation_entries SET state='pending' WHERE allocation_entries.scheme_id=?1 AND state='observed'
AND EXISTS(SELECT 1 FROM allocation_debits d JOIN allocation_windows w ON w.id=d.window_id
WHERE d.request_id=allocation_entries.request_id AND d.reconciled=0 AND w.reset_at<=?2)
`

type MarkExpiredAllocationEntriesParams struct {
	SchemeID int64
	ResetAt  int64
}

func (q *Queries) MarkExpiredAllocationEntries(ctx context.Context, arg MarkExpiredAllocationEntriesParams) error {
	_, err := q.db.ExecContext(ctx, markExpiredAllocationEntries, arg.SchemeID, arg.ResetAt)
	return err
}

const nextAllocationRevision = `-- name: NextAllocationRevision :one
SELECT id, scheme_id, effective_at, config FROM allocation_revisions WHERE scheme_id=? AND effective_at>? ORDER BY effective_at LIMIT 1
`

type NextAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
}

func (q *Queries) NextAllocationRevision(ctx context.Context, arg NextAllocationRevisionParams) (AllocationRevision, error) {
	row := q.db.QueryRowContext(ctx, nextAllocationRevision, arg.SchemeID, arg.EffectiveAt)
	var i AllocationRevision
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.EffectiveAt,
		&i.Config,
	)
	return i, err
}

const observeAllocationWindow = `-- name: ObserveAllocationWindow :exec
UPDATE allocation_windows SET observed_at=?,observed_points=?,unassigned=unassigned+? WHERE id=?
`

type ObserveAllocationWindowParams struct {
	ObservedAt     int64
	ObservedPoints int64
	Unassigned     int64
	ID             int64
}

func (q *Queries) ObserveAllocationWindow(ctx context.Context, arg ObserveAllocationWindowParams) error {
	_, err := q.db.ExecContext(ctx, observeAllocationWindow,
		arg.ObservedAt,
		arg.ObservedPoints,
		arg.Unassigned,
		arg.ID,
	)
	return err
}

const pruneAllocationWindows = `-- name: PruneAllocationWindows :exec
DELETE FROM allocation_windows WHERE reset_at<? AND unassigned=0
AND NOT EXISTS(SELECT 1 FROM allocation_debits WHERE window_id=allocation_windows.id)
`

func (q *Queries) PruneAllocationWindows(ctx context.Context, resetAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneAllocationWindows, resetAt)
	return err
}

const pruneAllocations = `-- name: PruneAllocations :exec
DELETE FROM allocation_entries WHERE state='settled' AND (
 (mode<>'ratio' AND allocation_entries.reset_at<?1) OR
 (mode='ratio' AND finished_at<?1*1000 AND NOT EXISTS(
 SELECT 1 FROM allocation_debits d JOIN allocation_windows w ON w.id=d.window_id
 WHERE d.request_id=allocation_entries.request_id AND (d.reconciled=0 OR w.reset_at>=?1)))
)
`

func (q *Queries) PruneAllocations(ctx context.Context, before int64) error {
	_, err := q.db.ExecContext(ctx, pruneAllocations, before)
	return err
}

const recoverAllocationEntries = `-- name: RecoverAllocationEntries :exec
UPDATE allocation_entries SET state='pending' WHERE state='active' AND EXISTS(
SELECT 1 FROM allocation_schemes s JOIN account_groups g ON g.id=s.group_id
WHERE s.id=allocation_entries.scheme_id AND g.tenant_id=?1)
`

func (q *Queries) RecoverAllocationEntries(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, recoverAllocationEntries, tenantID)
	return err
}

const revalidateAllocationWindow = `-- name: RevalidateAllocationWindow :exec
UPDATE allocation_windows SET account_revision=? WHERE id=?
`

type RevalidateAllocationWindowParams struct {
	AccountRevision int64
	ID              int64
}

func (q *Queries) RevalidateAllocationWindow(ctx context.Context, arg RevalidateAllocationWindowParams) error {
	_, err := q.db.ExecContext(ctx, revalidateAllocationWindow, arg.AccountRevision, arg.ID)
	return err
}

const saveAllocationRevision = `-- name: SaveAllocationRevision :execlastid
INSERT INTO allocation_revisions(scheme_id,effective_at,config) VALUES(?,?,?)
`

type SaveAllocationRevisionParams struct {
	SchemeID    int64
	EffectiveAt int64
	Config      string
}

func (q *Queries) SaveAllocationRevision(ctx context.Context, arg SaveAllocationRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAllocationRevision, arg.SchemeID, arg.EffectiveAt, arg.Config)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const setAllocationDebit = `-- name: SetAllocationDebit :exec
UPDATE allocation_debits SET points=?,reconciled=1 WHERE request_id=? AND window_id=?
`

type SetAllocationDebitParams struct {
	Points    int64
	RequestID string
	WindowID  int64
}

func (q *Queries) SetAllocationDebit(ctx context.Context, arg SetAllocationDebitParams) error {
	_, err := q.db.ExecContext(ctx, setAllocationDebit, arg.Points, arg.RequestID, arg.WindowID)
	return err
}

const settleReconciledAllocationEntries = `-- name: SettleReconciledAllocationEntries :exec
UPDATE allocation_entries SET state='settled' WHERE scheme_id=? AND state='observed'
AND NOT EXISTS(SELECT 1 FROM allocation_debits d WHERE d.request_id=allocation_entries.request_id AND d.reconciled=0)
`

func (q *Queries) SettleReconciledAllocationEntries(ctx context.Context, schemeID int64) error {
	_, err := q.db.ExecContext(ctx, settleReconciledAllocationEntries, schemeID)
	return err
}

const updateAllocationScheme = `-- name: UpdateAllocationScheme :exec
UPDATE allocation_schemes SET name=?,enabled=? WHERE id=?
`

type UpdateAllocationSchemeParams struct {
	Name    string
	Enabled int64
	ID      int64
}

func (q *Queries) UpdateAllocationScheme(ctx context.Context, arg UpdateAllocationSchemeParams) error {
	_, err := q.db.ExecContext(ctx, updateAllocationScheme, arg.Name, arg.Enabled, arg.ID)
	return err
}
