// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events(tenant_id,actor_id,actor_name,actor_role,source,action,resource,resource_id,outcome,http_status,created_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)
`

type CreateAuditEventParams struct {
	TenantID   int64
	ActorID    int64
	ActorName  string
	ActorRole  string
	Source     string
	Action     string
	Resource   string
	ResourceID string
	Outcome    string
	HttpStatus *int64
	CreatedAt  int64
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.TenantID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorRole,
		arg.Source,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Outcome,
		arg.HttpStatus,
		arg.CreatedAt,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, tenant_id, actor_id, actor_name, actor_role, source, "action", resource, resource_id, outcome, http_status, created_at FROM audit_events
WHERE tenant_id=?1 AND (id<?2 OR ?2=0)
AND (resource=?3 OR ?3='')
AND (outcome=?4 OR ?4='')
ORDER BY id DESC LIMIT 51
`

type ListAuditEventsParams struct {
	TenantID int64
	BeforeID int64
	Resource string
	Outcome  string
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.TenantID,
		arg.BeforeID,
		arg.Resource,
		arg.Outcome,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorRole,
			&i.Source,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Outcome,
			&i.HttpStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :exec
DELETE FROM audit_events AS current_event WHERE current_event.tenant_id=?1
AND (current_event.created_at<?2 OR current_event.id IN (
SELECT old_event.id FROM audit_events AS old_event WHERE old_event.tenant_id=?1
ORDER BY old_event.id DESC LIMIT -1 OFFSET 10000))
`

type PruneAuditEventsParams struct {
	ScopeTenantID int64
	Oldest        int64
}

func (q *Queries) PruneAuditEvents(ctx context.Context, arg PruneAuditEventsParams) error {
	_, err := q.db.ExecContext(ctx, pruneAuditEvents, arg.ScopeTenantID, arg.Oldest)
	return err
}
