// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events(actor_id,actor_name,actor_role,source,action,resource,resource_id,outcome,http_status,created_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)
`

type CreateAuditEventParams struct {
	ActorID    int64
	ActorName  string
	ActorRole  string
	Source     string
	Action     string
	Resource   string
	ResourceID string
	Outcome    string
	HttpStatus *int64
	CreatedAt  int64
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.ActorID,
		arg.ActorName,
		arg.ActorRole,
		arg.Source,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Outcome,
		arg.HttpStatus,
		arg.CreatedAt,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, actor_name, actor_role, source, "action", resource, resource_id, outcome, http_status, created_at FROM audit_events
WHERE (id<?1 OR ?1=0)
AND (resource=?2 OR ?2='')
AND (outcome=?3 OR ?3='')
ORDER BY id DESC LIMIT 51
`

type ListAuditEventsParams struct {
	BeforeID int64
	Resource string
	Outcome  string
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, arg.BeforeID, arg.Resource, arg.Outcome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorRole,
			&i.Source,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Outcome,
			&i.HttpStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :exec
DELETE FROM audit_events WHERE audit_events.created_at<?1 OR audit_events.id IN (SELECT id FROM audit_events ORDER BY id DESC LIMIT -1 OFFSET 10000)
`

func (q *Queries) PruneAuditEvents(ctx context.Context, oldest int64) error {
	_, err := q.db.ExecContext(ctx, pruneAuditEvents, oldest)
	return err
}
