// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const createAdministrator = `-- name: CreateAdministrator :execrows
INSERT INTO users(id, username, role, password_hash, created_at)
SELECT 1, ?1, 'admin', ?2, ?3
WHERE NOT EXISTS(SELECT 1 FROM users WHERE id = 1)
`

type CreateAdministratorParams struct {
	Username     string
	PasswordHash string
	CreatedAt    int64
}

func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdministrator, arg.Username, arg.PasswordHash, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(token_hash, user_id, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	return err
}

const getEnabledUser = `-- name: GetEnabledUser :one
SELECT id, username, role FROM users WHERE id = ?1 AND enabled = 1
`

type GetEnabledUserRow struct {
	ID       int64
	Username string
	Role     string
}

func (q *Queries) GetEnabledUser(ctx context.Context, id int64) (GetEnabledUserRow, error) {
	row := q.db.QueryRowContext(ctx, getEnabledUser, id)
	var i GetEnabledUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT id, username, role, password_hash FROM users
WHERE username = ?1 AND enabled = 1
`

type GetLoginUserRow struct {
	ID           int64
	Username     string
	Role         string
	PasswordHash string
}

func (q *Queries) GetLoginUser(ctx context.Context, username string) (GetLoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginUser, username)
	var i GetLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.role
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?1 AND s.expires_at > ?2 AND u.enabled = 1
`

type GetSessionUserParams struct {
	TokenHash []byte
	Now       int64
}

type GetSessionUserRow struct {
	ID       int64
	Username string
	Role     string
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.Now)
	var i GetSessionUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const hasAdministrator = `-- name: HasAdministrator :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = 1 AND role = 'admin')
`

func (q *Queries) HasAdministrator(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasAdministrator)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions WHERE token_hash = ?1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, revokeSession, tokenHash)
	return err
}

const trimSessions = `-- name: TrimSessions :exec
DELETE FROM sessions WHERE token_hash IN (
    SELECT s.token_hash FROM sessions s
    WHERE s.user_id = ?1 AND s.token_hash != ?2
    ORDER BY s.created_at DESC, s.rowid DESC LIMIT -1 OFFSET 4
)
`

type TrimSessionsParams struct {
	UserID           int64
	CurrentTokenHash []byte
}

func (q *Queries) TrimSessions(ctx context.Context, arg TrimSessionsParams) error {
	_, err := q.db.ExecContext(ctx, trimSessions, arg.UserID, arg.CurrentTokenHash)
	return err
}
