// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup.sql

package db

import (
	"context"
)

const countOversizedBackupRecords = `-- name: CountOversizedBackupRecords :one
SELECT count(*) FROM (
    SELECT 1 WHERE (SELECT count(*) FROM accounts) > 100
    UNION ALL
    SELECT 1 FROM accounts WHERE octet_length(id) > 64 OR octet_length(provider) > 32
      OR octet_length(name) > 256 OR octet_length(account_id) > 1024
      OR octet_length(email) > 1280 OR octet_length(plan) > 256
      OR octet_length(credential) > 262144
    UNION ALL
    SELECT 1 FROM api_keys WHERE octet_length(encrypted_secret) > 512 OR octet_length(token_hash) > 32
    LIMIT 1
)
`

// Match the account owner's bounded verification loop before scanning any credential rows.
func (q *Queries) CountOversizedBackupRecords(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOversizedBackupRecords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const revokeRestoredSessions = `-- name: RevokeRestoredSessions :exec
DELETE FROM sessions
`

func (q *Queries) RevokeRestoredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, revokeRestoredSessions)
	return err
}
