// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"
)

const addTokenBudgetUsage = `-- name: AddTokenBudgetUsage :exec
UPDATE token_budget_usage SET used=used+?1 WHERE budget_id=?2 AND window_start=?3
`

type AddTokenBudgetUsageParams struct {
	Tokens      int64
	BudgetID    int64
	WindowStart int64
}

func (q *Queries) AddTokenBudgetUsage(ctx context.Context, arg AddTokenBudgetUsageParams) error {
	_, err := q.db.ExecContext(ctx, addTokenBudgetUsage, arg.Tokens, arg.BudgetID, arg.WindowStart)
	return err
}

const beginTokenBudgetEntry = `-- name: BeginTokenBudgetEntry :exec
INSERT INTO token_budget_entries(request_id,budget_id,window_start,started_at,state) VALUES(?,?,?,?,'active')
`

type BeginTokenBudgetEntryParams struct {
	RequestID   string
	BudgetID    int64
	WindowStart int64
	StartedAt   int64
}

func (q *Queries) BeginTokenBudgetEntry(ctx context.Context, arg BeginTokenBudgetEntryParams) error {
	_, err := q.db.ExecContext(ctx, beginTokenBudgetEntry,
		arg.RequestID,
		arg.BudgetID,
		arg.WindowStart,
		arg.StartedAt,
	)
	return err
}

const beginTokenBudgetUsage = `-- name: BeginTokenBudgetUsage :exec
INSERT INTO token_budget_usage(budget_id,window_start,window_end) VALUES(?,?,?) ON CONFLICT DO NOTHING
`

type BeginTokenBudgetUsageParams struct {
	BudgetID    int64
	WindowStart int64
	WindowEnd   int64
}

func (q *Queries) BeginTokenBudgetUsage(ctx context.Context, arg BeginTokenBudgetUsageParams) error {
	_, err := q.db.ExecContext(ctx, beginTokenBudgetUsage, arg.BudgetID, arg.WindowStart, arg.WindowEnd)
	return err
}

const countTokenBudgetPending = `-- name: CountTokenBudgetPending :one
SELECT count(*) FROM token_budget_entries WHERE budget_id=? AND state='pending'
`

func (q *Queries) CountTokenBudgetPending(ctx context.Context, budgetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTokenBudgetPending, budgetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTokenBudgetUsage = `-- name: GetTokenBudgetUsage :one
SELECT used FROM token_budget_usage WHERE budget_id=? AND window_start=?
`

type GetTokenBudgetUsageParams struct {
	BudgetID    int64
	WindowStart int64
}

func (q *Queries) GetTokenBudgetUsage(ctx context.Context, arg GetTokenBudgetUsageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTokenBudgetUsage, arg.BudgetID, arg.WindowStart)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const listPendingTokenRequests = `-- name: ListPendingTokenRequests :many
SELECT e.request_id, CAST(min(e.started_at) AS INTEGER) AS started_at, CAST(max(e.tokens) AS INTEGER) AS known_tokens
FROM token_budget_entries e JOIN token_budgets b ON b.id=e.budget_id
WHERE b.tenant_id=?1 AND b.user_id=?2 AND e.state='pending' GROUP BY e.request_id ORDER BY started_at LIMIT 256
`

type ListPendingTokenRequestsParams struct {
	TenantID int64
	UserID   int64
}

type ListPendingTokenRequestsRow struct {
	RequestID   string
	StartedAt   int64
	KnownTokens int64
}

func (q *Queries) ListPendingTokenRequests(ctx context.Context, arg ListPendingTokenRequestsParams) ([]ListPendingTokenRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTokenRequests, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingTokenRequestsRow{}
	for rows.Next() {
		var i ListPendingTokenRequestsRow
		if err := rows.Scan(&i.RequestID, &i.StartedAt, &i.KnownTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenBudgetEntries = `-- name: ListTokenBudgetEntries :many
SELECT e.request_id, e.budget_id, e.window_start, e.started_at, e.state, e.tokens, e.manual FROM token_budget_entries e JOIN token_budgets b ON b.id=e.budget_id
WHERE e.request_id=?1 AND b.user_id=?2 AND b.tenant_id=?3 ORDER BY e.budget_id
`

type ListTokenBudgetEntriesParams struct {
	RequestID string
	UserID    int64
	TenantID  int64
}

func (q *Queries) ListTokenBudgetEntries(ctx context.Context, arg ListTokenBudgetEntriesParams) ([]TokenBudgetEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTokenBudgetEntries, arg.RequestID, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenBudgetEntry{}
	for rows.Next() {
		var i TokenBudgetEntry
		if err := rows.Scan(
			&i.RequestID,
			&i.BudgetID,
			&i.WindowStart,
			&i.StartedAt,
			&i.State,
			&i.Tokens,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenBudgets = `-- name: ListTokenBudgets :many
SELECT b.id, b.tenant_id, b.user_id, b.group_id, b.model, b.period, b.token_limit, b.enabled, b.created_at, COALESCE(g.name,'') AS group_name FROM token_budgets b
LEFT JOIN account_groups g ON g.id=b.group_id WHERE b.tenant_id=?1 AND b.user_id=?2 ORDER BY b.id
`

type ListTokenBudgetsParams struct {
	TenantID int64
	UserID   int64
}

type ListTokenBudgetsRow struct {
	ID         int64
	TenantID   int64
	UserID     int64
	GroupID    int64
	Model      string
	Period     string
	TokenLimit int64
	Enabled    int64
	CreatedAt  int64
	GroupName  string
}

func (q *Queries) ListTokenBudgets(ctx context.Context, arg ListTokenBudgetsParams) ([]ListTokenBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenBudgets, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenBudgetsRow{}
	for rows.Next() {
		var i ListTokenBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.GroupID,
			&i.Model,
			&i.Period,
			&i.TokenLimit,
			&i.Enabled,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTokenBudgetEntries = `-- name: PruneTokenBudgetEntries :exec
DELETE FROM token_budget_entries WHERE state='settled' AND started_at<?1
`

func (q *Queries) PruneTokenBudgetEntries(ctx context.Context, beforeTime int64) error {
	_, err := q.db.ExecContext(ctx, pruneTokenBudgetEntries, beforeTime)
	return err
}

const pruneTokenBudgetUsage = `-- name: PruneTokenBudgetUsage :exec
DELETE FROM token_budget_usage WHERE window_end<?1
AND NOT EXISTS(SELECT 1 FROM token_budget_entries e WHERE e.budget_id=token_budget_usage.budget_id AND e.window_start=token_budget_usage.window_start)
`

func (q *Queries) PruneTokenBudgetUsage(ctx context.Context, beforeTime int64) error {
	_, err := q.db.ExecContext(ctx, pruneTokenBudgetUsage, beforeTime)
	return err
}

const recoverTokenBudgetEntries = `-- name: RecoverTokenBudgetEntries :exec
UPDATE token_budget_entries SET state='pending' WHERE state='active'
AND EXISTS(SELECT 1 FROM token_budgets b WHERE b.id=token_budget_entries.budget_id AND b.tenant_id=?1)
`

func (q *Queries) RecoverTokenBudgetEntries(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, recoverTokenBudgetEntries, tenantID)
	return err
}

const saveTokenBudget = `-- name: SaveTokenBudget :one
INSERT INTO token_budgets(tenant_id,user_id,group_id,model,period,token_limit,enabled,created_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8) ON CONFLICT(tenant_id,user_id,group_id,model,period)
DO UPDATE SET token_limit=excluded.token_limit,enabled=excluded.enabled RETURNING id
`

type SaveTokenBudgetParams struct {
	TenantID   int64
	UserID     int64
	GroupID    int64
	Model      string
	Period     string
	TokenLimit int64
	Enabled    int64
	CreatedAt  int64
}

func (q *Queries) SaveTokenBudget(ctx context.Context, arg SaveTokenBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveTokenBudget,
		arg.TenantID,
		arg.UserID,
		arg.GroupID,
		arg.Model,
		arg.Period,
		arg.TokenLimit,
		arg.Enabled,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setTokenBudgetEntry = `-- name: SetTokenBudgetEntry :exec
UPDATE token_budget_entries SET state=?,tokens=?,manual=? WHERE request_id=? AND budget_id=?
`

type SetTokenBudgetEntryParams struct {
	State     string
	Tokens    int64
	Manual    int64
	RequestID string
	BudgetID  int64
}

func (q *Queries) SetTokenBudgetEntry(ctx context.Context, arg SetTokenBudgetEntryParams) error {
	_, err := q.db.ExecContext(ctx, setTokenBudgetEntry,
		arg.State,
		arg.Tokens,
		arg.Manual,
		arg.RequestID,
		arg.BudgetID,
	)
	return err
}
