// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const getAccountCatalog = `-- name: GetAccountCatalog :one
SELECT models_snapshot, models_revision FROM accounts WHERE id = ?1
`

type GetAccountCatalogRow struct {
	ModelsSnapshot []byte
	ModelsRevision int64
}

func (q *Queries) GetAccountCatalog(ctx context.Context, id string) (GetAccountCatalogRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountCatalog, id)
	var i GetAccountCatalogRow
	err := row.Scan(&i.ModelsSnapshot, &i.ModelsRevision)
	return i, err
}

const invalidateAccountCatalog = `-- name: InvalidateAccountCatalog :exec
UPDATE accounts SET models_snapshot = NULL, models_revision = models_revision + 1
WHERE id = ?1
`

func (q *Queries) InvalidateAccountCatalog(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, invalidateAccountCatalog, id)
	return err
}

const listGroupCatalogs = `-- name: ListGroupCatalogs :many
SELECT a.id, a.provider, a.models_snapshot, a.models_revision
FROM accounts a JOIN group_accounts ga ON ga.account_id = a.id
WHERE ga.group_id = ?1 AND a.enabled = 1 AND a.status != 'reauth_required'
ORDER BY a.id
`

type ListGroupCatalogsRow struct {
	ID             string
	Provider       string
	ModelsSnapshot []byte
	ModelsRevision int64
}

func (q *Queries) ListGroupCatalogs(ctx context.Context, groupID int64) ([]ListGroupCatalogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupCatalogs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupCatalogsRow{}
	for rows.Next() {
		var i ListGroupCatalogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelsSnapshot,
			&i.ModelsRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAccountCatalog = `-- name: SaveAccountCatalog :execrows
UPDATE accounts SET models_snapshot = ?1
WHERE id = ?2 AND models_revision = ?3
AND enabled = 1 AND status != 'reauth_required'
AND COALESCE(json_extract(models_snapshot, '$.updated_at'), 0) <= CAST(?4 AS INTEGER)
`

type SaveAccountCatalogParams struct {
	Snapshot   []byte
	ID         string
	Revision   int64
	ObservedAt int64
}

func (q *Queries) SaveAccountCatalog(ctx context.Context, arg SaveAccountCatalogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAccountCatalog,
		arg.Snapshot,
		arg.ID,
		arg.Revision,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
