// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"
)

const countContentSecrets = `-- name: CountContentSecrets :one
SELECT COUNT(*) FROM tenants WHERE length(content_config)>0
`

func (q *Queries) CountContentSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContentSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContentConfig = `-- name: GetContentConfig :one
SELECT content_config FROM tenants WHERE id=? AND status='active'
`

func (q *Queries) GetContentConfig(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getContentConfig, id)
	var content_config []byte
	err := row.Scan(&content_config)
	return content_config, err
}

const listContentConfigs = `-- name: ListContentConfigs :many
SELECT id,content_config FROM tenants WHERE length(content_config)>0
`

type ListContentConfigsRow struct {
	ID            int64
	ContentConfig []byte
}

func (q *Queries) ListContentConfigs(ctx context.Context) ([]ListContentConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContentConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentConfigsRow{}
	for rows.Next() {
		var i ListContentConfigsRow
		if err := rows.Scan(&i.ID, &i.ContentConfig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveContentConfig = `-- name: SaveContentConfig :execrows
UPDATE tenants SET content_config=?1 WHERE id=?2 AND status='active' AND content_config=COALESCE(?3,X'')
`

type SaveContentConfigParams struct {
	Config   []byte
	TenantID int64
	Previous []byte
}

func (q *Queries) SaveContentConfig(ctx context.Context, arg SaveContentConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveContentConfig, arg.Config, arg.TenantID, arg.Previous)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
