// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway.sql

package db

import (
	"context"
)

const countAccountAffinity = `-- name: CountAccountAffinity :one
SELECT count(*) FROM account_affinity
`

func (q *Queries) CountAccountAffinity(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountAffinity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountAffinity = `-- name: CreateAccountAffinity :exec
INSERT INTO account_affinity(user_id, group_id, session_hash, provider, account_id, expires_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateAccountAffinityParams struct {
	UserID      int64
	GroupID     int64
	SessionHash []byte
	Provider    string
	AccountID   string
	ExpiresAt   int64
}

func (q *Queries) CreateAccountAffinity(ctx context.Context, arg CreateAccountAffinityParams) error {
	_, err := q.db.ExecContext(ctx, createAccountAffinity,
		arg.UserID,
		arg.GroupID,
		arg.SessionHash,
		arg.Provider,
		arg.AccountID,
		arg.ExpiresAt,
	)
	return err
}

const listSessionAffinities = `-- name: ListSessionAffinities :many
SELECT provider, account_id, expires_at FROM account_affinity
WHERE user_id = ?1 AND group_id = ?2
AND session_hash = ?3 AND expires_at > ?4
ORDER BY provider
`

type ListSessionAffinitiesParams struct {
	UserID      int64
	GroupID     int64
	SessionHash []byte
	Now         int64
}

type ListSessionAffinitiesRow struct {
	Provider  string
	AccountID string
	ExpiresAt int64
}

func (q *Queries) ListSessionAffinities(ctx context.Context, arg ListSessionAffinitiesParams) ([]ListSessionAffinitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionAffinities,
		arg.UserID,
		arg.GroupID,
		arg.SessionHash,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionAffinitiesRow{}
	for rows.Next() {
		var i ListSessionAffinitiesRow
		if err := rows.Scan(&i.Provider, &i.AccountID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAccountAffinity = `-- name: PruneAccountAffinity :exec
DELETE FROM account_affinity WHERE expires_at <= ?1
`

func (q *Queries) PruneAccountAffinity(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, pruneAccountAffinity, now)
	return err
}

const touchAccountAffinity = `-- name: TouchAccountAffinity :exec
UPDATE account_affinity SET expires_at = ?1 WHERE user_id = ?2 AND group_id = ?3 AND session_hash = ?4 AND provider = ?5 AND expires_at < ?6
`

type TouchAccountAffinityParams struct {
	ExpiresAt   int64
	UserID      int64
	GroupID     int64
	SessionHash []byte
	Provider    string
	Threshold   int64
}

func (q *Queries) TouchAccountAffinity(ctx context.Context, arg TouchAccountAffinityParams) error {
	_, err := q.db.ExecContext(ctx, touchAccountAffinity,
		arg.ExpiresAt,
		arg.UserID,
		arg.GroupID,
		arg.SessionHash,
		arg.Provider,
		arg.Threshold,
	)
	return err
}
