// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
)

const addGroupAccount = `-- name: AddGroupAccount :exec
INSERT INTO group_accounts(group_id,account_id) VALUES(?1,?2)
`

type AddGroupAccountParams struct {
	GroupID   int64
	AccountID string
}

func (q *Queries) AddGroupAccount(ctx context.Context, arg AddGroupAccountParams) error {
	_, err := q.db.ExecContext(ctx, addGroupAccount, arg.GroupID, arg.AccountID)
	return err
}

const addGroupModel = `-- name: AddGroupModel :exec
INSERT INTO group_models(group_id,model) VALUES(?1,?2)
`

type AddGroupModelParams struct {
	GroupID int64
	Model   string
}

func (q *Queries) AddGroupModel(ctx context.Context, arg AddGroupModelParams) error {
	_, err := q.db.ExecContext(ctx, addGroupModel, arg.GroupID, arg.Model)
	return err
}

const canUseGroup = `-- name: CanUseGroup :one
SELECT EXISTS(SELECT 1 FROM account_groups g JOIN users u ON u.id=?1
WHERE g.id=?2 AND g.enabled=1 AND u.enabled=1
AND EXISTS(SELECT 1 FROM effective_group_access access WHERE access.group_id=g.id AND access.user_id=u.id))
`

type CanUseGroupParams struct {
	UserID  int64
	GroupID int64
}

func (q *Queries) CanUseGroup(ctx context.Context, arg CanUseGroupParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canUseGroup, arg.UserID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearGroupAccounts = `-- name: ClearGroupAccounts :exec
DELETE FROM group_accounts WHERE group_id=?1
`

func (q *Queries) ClearGroupAccounts(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, clearGroupAccounts, groupID)
	return err
}

const clearGroupModels = `-- name: ClearGroupModels :exec
DELETE FROM group_models WHERE group_id=?1
`

func (q *Queries) ClearGroupModels(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, clearGroupModels, groupID)
	return err
}

const clearMemberGroups = `-- name: ClearMemberGroups :exec
DELETE FROM group_members WHERE user_id=?1
`

func (q *Queries) ClearMemberGroups(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearMemberGroups, userID)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM effective_group_access m JOIN users u ON u.id=m.user_id WHERE m.group_id=?1 AND u.role='member'
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT count(*) FROM account_groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :execlastid
INSERT INTO account_groups(name,enabled,created_at,updated_at)
VALUES(?1,?2,?3,?3)
`

type CreateGroupParams struct {
	Name    string
	Enabled bool
	Now     int64
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGroup, arg.Name, arg.Enabled, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const findGroupName = `-- name: FindGroupName :one
SELECT id FROM account_groups WHERE name=?1 COLLATE NOCASE
`

func (q *Queries) FindGroupName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findGroupName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, enabled, created_at, updated_at, restricted_models FROM account_groups WHERE id=?1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (AccountGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i AccountGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RestrictedModels,
	)
	return i, err
}

const grantMemberGroup = `-- name: GrantMemberGroup :exec
INSERT INTO group_members(group_id,user_id) VALUES(?1,?2)
`

type GrantMemberGroupParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) GrantMemberGroup(ctx context.Context, arg GrantMemberGroupParams) error {
	_, err := q.db.ExecContext(ctx, grantMemberGroup, arg.GroupID, arg.UserID)
	return err
}

const groupAccountExists = `-- name: GroupAccountExists :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE id=?1)
`

func (q *Queries) GroupAccountExists(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, groupAccountExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupConnectionStatus = `-- name: GroupConnectionStatus :one
SELECT CASE WHEN EXISTS(
 SELECT 1 FROM group_accounts ga JOIN accounts a ON a.id=ga.account_id JOIN account_groups g ON g.id=ga.group_id JOIN users u ON u.id=?1
 WHERE g.enabled=1 AND a.enabled=1 AND a.status='ready' AND u.enabled=1 AND EXISTS(SELECT 1 FROM effective_group_access access WHERE access.group_id=g.id AND access.user_id=u.id)
) THEN 'ready' WHEN EXISTS(
 SELECT 1 FROM group_accounts ga JOIN accounts a ON a.id=ga.account_id JOIN account_groups g ON g.id=ga.group_id JOIN users u ON u.id=?1
 WHERE g.enabled=1 AND a.enabled=1 AND u.enabled=1 AND EXISTS(SELECT 1 FROM effective_group_access access WHERE access.group_id=g.id AND access.user_id=u.id)
) THEN 'needs_attention' ELSE 'not_configured' END AS status
`

func (q *Queries) GroupConnectionStatus(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, groupConnectionStatus, userID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listAvailableGroups = `-- name: ListAvailableGroups :many
SELECT g.id,g.name FROM account_groups g JOIN users u ON u.id=?1
WHERE g.enabled=1 AND u.enabled=1
AND EXISTS(SELECT 1 FROM effective_group_access access WHERE access.group_id=g.id AND access.user_id=u.id) ORDER BY g.id
`

type ListAvailableGroupsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListAvailableGroups(ctx context.Context, userID int64) ([]ListAvailableGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableGroupsRow{}
	for rows.Next() {
		var i ListAvailableGroupsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupAccounts = `-- name: ListGroupAccounts :many
SELECT account_id FROM group_accounts WHERE group_id=?1 ORDER BY account_id
`

func (q *Queries) ListGroupAccounts(ctx context.Context, groupID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGroupAccounts, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupModels = `-- name: ListGroupModels :many
SELECT model FROM group_models WHERE group_id=?1 ORDER BY model
`

func (q *Queries) ListGroupModels(ctx context.Context, groupID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGroupModels, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.enabled, g.created_at, g.updated_at, g.restricted_models, (SELECT count(*) FROM group_accounts a WHERE a.group_id=g.id) AS account_count,
(SELECT count(*) FROM effective_group_access m JOIN users u ON u.id=m.user_id WHERE m.group_id=g.id AND u.role='member') AS member_count
FROM account_groups g ORDER BY g.id
`

type ListGroupsRow struct {
	ID               int64
	Name             string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	RestrictedModels bool
	AccountCount     int64
	MemberCount      int64
}

func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RestrictedModels,
			&i.AccountCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberGroups = `-- name: ListMemberGroups :many
SELECT group_id FROM group_members WHERE user_id=?1 ORDER BY group_id
`

func (q *Queries) ListMemberGroups(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listMemberGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupModelPolicy = `-- name: SetGroupModelPolicy :exec
UPDATE account_groups SET restricted_models=?1 WHERE id=?2
`

type SetGroupModelPolicyParams struct {
	Restricted bool
	ID         int64
}

func (q *Queries) SetGroupModelPolicy(ctx context.Context, arg SetGroupModelPolicyParams) error {
	_, err := q.db.ExecContext(ctx, setGroupModelPolicy, arg.Restricted, arg.ID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE account_groups SET name=?1,enabled=?2,updated_at=?3 WHERE id=?4
`

type UpdateGroupParams struct {
	Name    string
	Enabled bool
	Now     int64
	ID      int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup,
		arg.Name,
		arg.Enabled,
		arg.Now,
		arg.ID,
	)
	return err
}
