// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
)

const consumeInvitation = `-- name: ConsumeInvitation :execrows
UPDATE invitations SET used_at=?1, used_by=?2
WHERE id=?3 AND used_at IS NULL AND expires_at>?1
`

type ConsumeInvitationParams struct {
	UsedAt *int64
	UsedBy *int64
	ID     int64
}

func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeInvitation, arg.UsedAt, arg.UsedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations(token_hash, tenant_id, created_by, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id
`

type CreateInvitationParams struct {
	TokenHash []byte
	TenantID  int64
	CreatedBy int64
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.TokenHash,
		arg.TenantID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUsableInvitation = `-- name: GetUsableInvitation :one
SELECT i.id FROM invitations i JOIN tenants t ON t.id=i.tenant_id
WHERE i.token_hash=?1 AND i.tenant_id=?2
AND i.expires_at>?3 AND i.used_at IS NULL AND t.status='active'
`

type GetUsableInvitationParams struct {
	TokenHash []byte
	TenantID  int64
	Now       int64
}

func (q *Queries) GetUsableInvitation(ctx context.Context, arg GetUsableInvitationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUsableInvitation, arg.TokenHash, arg.TenantID, arg.Now)
	var id int64
	err := row.Scan(&id)
	return id, err
}
