// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package db

import (
	"context"
)

const authenticateKey = `-- name: AuthenticateKey :one
SELECT k.id,k.user_id,k.group_id FROM api_keys k JOIN users u ON u.id=k.user_id JOIN account_groups g ON g.id=k.group_id
WHERE k.token_hash=?1 AND k.revoked_at IS NULL AND u.enabled=1 AND g.enabled=1
AND (u.role='admin' OR EXISTS(SELECT 1 FROM group_members m WHERE m.group_id=g.id AND m.user_id=u.id))
`

type AuthenticateKeyRow struct {
	ID      int64
	UserID  int64
	GroupID int64
}

func (q *Queries) AuthenticateKey(ctx context.Context, tokenHash []byte) (AuthenticateKeyRow, error) {
	row := q.db.QueryRowContext(ctx, authenticateKey, tokenHash)
	var i AuthenticateKeyRow
	err := row.Scan(&i.ID, &i.UserID, &i.GroupID)
	return i, err
}

const countActiveKeys = `-- name: CountActiveKeys :one
SELECT count(*) FROM api_keys WHERE user_id = ?1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveKeys(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKey = `-- name: CreateKey :execlastid
INSERT INTO api_keys(user_id,group_id,name,prefix,token_hash,created_at)
VALUES(?1,?2,?3,?4,?5,?6)
`

type CreateKeyParams struct {
	UserID    int64
	GroupID   int64
	Name      string
	Prefix    string
	TokenHash []byte
	CreatedAt int64
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createKey,
		arg.UserID,
		arg.GroupID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getKey = `-- name: GetKey :one
SELECT k.id,k.group_id,g.name AS group_name,
CASE WHEN g.enabled=1 AND u.enabled=1 AND (u.role='admin' OR EXISTS(SELECT 1 FROM group_members m WHERE m.group_id=g.id AND m.user_id=u.id)) THEN 'allowed' ELSE 'blocked' END AS group_access,
k.name,k.prefix,k.created_at,k.last_used_at,k.revoked_at
FROM api_keys k JOIN account_groups g ON g.id=k.group_id JOIN users u ON u.id=k.user_id
WHERE k.id=?1 AND k.user_id=?2
`

type GetKeyParams struct {
	ID     int64
	UserID int64
}

type GetKeyRow struct {
	ID          int64
	GroupID     int64
	GroupName   string
	GroupAccess string
	Name        string
	Prefix      string
	CreatedAt   int64
	LastUsedAt  *int64
	RevokedAt   *int64
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getKey, arg.ID, arg.UserID)
	var i GetKeyRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.GroupName,
		&i.GroupAccess,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getKeyOwnerEnabled = `-- name: GetKeyOwnerEnabled :one
SELECT enabled FROM users WHERE id = ?1
`

func (q *Queries) GetKeyOwnerEnabled(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, getKeyOwnerEnabled, userID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listKeys = `-- name: ListKeys :many
SELECT k.id,k.group_id,g.name AS group_name,
CASE WHEN g.enabled=1 AND u.enabled=1 AND (u.role='admin' OR EXISTS(SELECT 1 FROM group_members m WHERE m.group_id=g.id AND m.user_id=u.id)) THEN 'allowed' ELSE 'blocked' END AS group_access,
k.name,k.prefix,k.created_at,k.last_used_at,k.revoked_at
FROM api_keys k JOIN account_groups g ON g.id=k.group_id JOIN users u ON u.id=k.user_id
WHERE k.user_id=?1 AND (k.id<?2 OR ?2=0)
ORDER BY k.id DESC LIMIT 51
`

type ListKeysParams struct {
	UserID   int64
	BeforeID int64
}

type ListKeysRow struct {
	ID          int64
	GroupID     int64
	GroupName   string
	GroupAccess string
	Name        string
	Prefix      string
	CreatedAt   int64
	LastUsedAt  *int64
	RevokedAt   *int64
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, arg.UserID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysRow{}
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GroupName,
			&i.GroupAccess,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeKey = `-- name: RevokeKey :execrows
UPDATE api_keys SET revoked_at=COALESCE(revoked_at,?1) WHERE id=?2 AND user_id=?3
`

type RevokeKeyParams struct {
	Now    *int64
	ID     int64
	UserID int64
}

func (q *Queries) RevokeKey(ctx context.Context, arg RevokeKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeKey, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchKey = `-- name: TouchKey :exec
UPDATE api_keys SET last_used_at = ?1
WHERE id = ?2 AND revoked_at IS NULL
AND (last_used_at IS NULL OR last_used_at <= ?3)
`

type TouchKeyParams struct {
	Now       *int64
	ID        int64
	Threshold *int64
}

func (q *Queries) TouchKey(ctx context.Context, arg TouchKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchKey, arg.Now, arg.ID, arg.Threshold)
	return err
}
