// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package db

import (
	"context"
)

const authenticateKey = `-- name: AuthenticateKey :one
SELECT k.id, k.user_id FROM api_keys k JOIN users u ON u.id = k.user_id
WHERE k.token_hash = ?1 AND k.revoked_at IS NULL AND u.enabled = 1
`

type AuthenticateKeyRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) AuthenticateKey(ctx context.Context, tokenHash []byte) (AuthenticateKeyRow, error) {
	row := q.db.QueryRowContext(ctx, authenticateKey, tokenHash)
	var i AuthenticateKeyRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const countActiveKeys = `-- name: CountActiveKeys :one
SELECT count(*) FROM api_keys WHERE user_id = ?1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveKeys(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKey = `-- name: CreateKey :execlastid
INSERT INTO api_keys(user_id, name, prefix, token_hash, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateKeyParams struct {
	UserID    int64
	Name      string
	Prefix    string
	TokenHash []byte
	CreatedAt int64
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getKeyOwnerEnabled = `-- name: GetKeyOwnerEnabled :one
SELECT enabled FROM users WHERE id = ?1
`

func (q *Queries) GetKeyOwnerEnabled(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, getKeyOwnerEnabled, userID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listKeys = `-- name: ListKeys :many
SELECT id, name, prefix, created_at, last_used_at, revoked_at FROM api_keys
WHERE user_id = ?1 AND (id < ?2 OR ?2 = 0)
ORDER BY id DESC LIMIT 51
`

type ListKeysParams struct {
	UserID   int64
	BeforeID int64
}

type ListKeysRow struct {
	ID         int64
	Name       string
	Prefix     string
	CreatedAt  int64
	LastUsedAt *int64
	RevokedAt  *int64
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, arg.UserID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysRow{}
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeKey = `-- name: RevokeKey :one
UPDATE api_keys SET revoked_at = COALESCE(revoked_at, ?1)
WHERE id = ?2 AND user_id = ?3
RETURNING id, name, prefix, created_at, last_used_at, revoked_at
`

type RevokeKeyParams struct {
	Now    *int64
	ID     int64
	UserID int64
}

type RevokeKeyRow struct {
	ID         int64
	Name       string
	Prefix     string
	CreatedAt  int64
	LastUsedAt *int64
	RevokedAt  *int64
}

func (q *Queries) RevokeKey(ctx context.Context, arg RevokeKeyParams) (RevokeKeyRow, error) {
	row := q.db.QueryRowContext(ctx, revokeKey, arg.Now, arg.ID, arg.UserID)
	var i RevokeKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchKey = `-- name: TouchKey :exec
UPDATE api_keys SET last_used_at = ?1
WHERE id = ?2 AND revoked_at IS NULL
AND (last_used_at IS NULL OR last_used_at <= ?3)
`

type TouchKeyParams struct {
	Now       *int64
	ID        int64
	Threshold *int64
}

func (q *Queries) TouchKey(ctx context.Context, arg TouchKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchKey, arg.Now, arg.ID, arg.Threshold)
	return err
}
