// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package db

import (
	"context"
)

const getMemberLimits = `-- name: GetMemberLimits :one
SELECT u.id,u.role,u.enabled,CAST(COALESCE(l.requests_per_minute,0) AS INTEGER) AS requests_per_minute,CAST(COALESCE(l.max_concurrency,0) AS INTEGER) AS max_concurrency
FROM users u LEFT JOIN member_limits l ON l.user_id=u.id WHERE u.id=?1
`

type GetMemberLimitsRow struct {
	ID                int64
	Role              string
	Enabled           bool
	RequestsPerMinute int64
	MaxConcurrency    int64
}

func (q *Queries) GetMemberLimits(ctx context.Context, userID int64) (GetMemberLimitsRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberLimits, userID)
	var i GetMemberLimitsRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Enabled,
		&i.RequestsPerMinute,
		&i.MaxConcurrency,
	)
	return i, err
}

const getMemberWindow = `-- name: GetMemberWindow :one
SELECT window_start,requests FROM member_rate WHERE user_id=?1
`

type GetMemberWindowRow struct {
	WindowStart int64
	Requests    int64
}

func (q *Queries) GetMemberWindow(ctx context.Context, userID int64) (GetMemberWindowRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberWindow, userID)
	var i GetMemberWindowRow
	err := row.Scan(&i.WindowStart, &i.Requests)
	return i, err
}

const setMemberLimits = `-- name: SetMemberLimits :execrows
INSERT INTO member_limits(user_id,requests_per_minute,max_concurrency)
SELECT id,?1,?2 FROM users WHERE id=?3 AND role='member'
ON CONFLICT(user_id) DO UPDATE SET requests_per_minute=excluded.requests_per_minute,max_concurrency=excluded.max_concurrency
`

type SetMemberLimitsParams struct {
	RequestsPerMinute int64
	MaxConcurrency    int64
	UserID            int64
}

func (q *Queries) SetMemberLimits(ctx context.Context, arg SetMemberLimitsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMemberLimits, arg.RequestsPerMinute, arg.MaxConcurrency, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const takeMemberRate = `-- name: TakeMemberRate :execrows
INSERT INTO member_rate(user_id,window_start,requests)
SELECT ?1,?2,1
WHERE NOT EXISTS(SELECT 1 FROM member_rate r WHERE r.user_id=?1 AND r.window_start=?2 AND r.requests>=?3)
ON CONFLICT(user_id) DO UPDATE SET window_start=excluded.window_start,requests=CASE WHEN member_rate.window_start=excluded.window_start THEN member_rate.requests+1 ELSE 1 END
`

type TakeMemberRateParams struct {
	UserID      int64
	WindowStart int64
	RateLimit   int64
}

func (q *Queries) TakeMemberRate(ctx context.Context, arg TakeMemberRateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, takeMemberRate, arg.UserID, arg.WindowStart, arg.RateLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
