// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO users(username, role, password_hash, created_at)
VALUES (?1, 'member', ?2, ?3)
ON CONFLICT(username) DO NOTHING
RETURNING id, username, role, enabled, created_at
`

type CreateMemberParams struct {
	Username     string
	PasswordHash string
	CreatedAt    int64
}

type CreateMemberRow struct {
	ID        int64
	Username  string
	Role      string
	Enabled   bool
	CreatedAt int64
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (CreateMemberRow, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.Username, arg.PasswordHash, arg.CreatedAt)
	var i CreateMemberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, username, role, enabled, created_at FROM users
WHERE id = ?1 AND role = 'member'
`

type GetMemberRow struct {
	ID        int64
	Username  string
	Role      string
	Enabled   bool
	CreatedAt int64
}

func (q *Queries) GetMember(ctx context.Context, id int64) (GetMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, username, role, enabled, created_at FROM users
WHERE role = 'member' AND (id < ?1 OR ?1 = 0)
ORDER BY id DESC LIMIT 51
`

type ListMembersRow struct {
	ID        int64
	Username  string
	Role      string
	Enabled   bool
	CreatedAt int64
}

func (q *Queries) ListMembers(ctx context.Context, beforeID int64) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, beforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberEnabled = `-- name: SetMemberEnabled :exec
UPDATE users SET enabled = ?1 WHERE id = ?2
`

type SetMemberEnabledParams struct {
	Enabled bool
	ID      int64
}

func (q *Queries) SetMemberEnabled(ctx context.Context, arg SetMemberEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setMemberEnabled, arg.Enabled, arg.ID)
	return err
}
