// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID             string
	Provider       string
	Name           string
	AccountID      string
	Email          string
	Plan           string
	Enabled        bool
	Status         string
	Credential     []byte
	ExpiresAt      int64
	CreatedAt      int64
	UpdatedAt      int64
	MaxConcurrency int64
	ModelsSnapshot []byte
	ModelsRevision int64
	TenantID       int64
}

type AccountGroup struct {
	ID               int64
	Name             string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	RestrictedModels bool
	TenantID         int64
}

type AllocationEntry struct {
	RequestID    string
	SchemeID     int64
	RevisionID   int64
	UserID       int64
	AccountID    string
	Model        string
	Mode         string
	WindowStart  int64
	ResetAt      int64
	StartedAt    int64
	FinishedAt   int64
	State        string
	InputTokens  int64
	OutputTokens int64
	CachedTokens int64
	Cost         int64
	Manual       int64
}

type AllocationRevision struct {
	ID          int64
	SchemeID    int64
	EffectiveAt int64
	Config      string
}

type AllocationWindow struct {
	ID              int64
	SchemeID        int64
	AccountID       string
	Kind            string
	ResetAt         int64
	AccountRevision int64
	ObservedAt      int64
	ObservedPoints  int64
	BaselinePoints  int64
	Unassigned      int64
}

type AuditEvent struct {
	ID         int64
	TenantID   int64
	ActorID    int64
	ActorName  string
	ActorRole  string
	Source     string
	Action     string
	Resource   string
	ResourceID string
	Outcome    string
	HttpStatus *int64
	CreatedAt  int64
}

type TokenBudgetEntry struct {
	RequestID   string
	BudgetID    int64
	WindowStart int64
	StartedAt   int64
	State       string
	Tokens      int64
	Manual      int64
}
