// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID             string
	Provider       string
	Name           string
	AccountID      string
	Email          string
	Plan           string
	Enabled        bool
	Status         string
	Credential     []byte
	ExpiresAt      int64
	CreatedAt      int64
	UpdatedAt      int64
	MaxConcurrency int64
	ModelsSnapshot []byte
	ModelsRevision int64
}

type AccountGroup struct {
	ID               int64
	Name             string
	Enabled          bool
	CreatedAt        int64
	UpdatedAt        int64
	RestrictedModels bool
}

type AuditEvent struct {
	ID         int64
	ActorID    int64
	ActorName  string
	ActorRole  string
	Source     string
	Action     string
	Resource   string
	ResourceID string
	Outcome    string
	HttpStatus *int64
	CreatedAt  int64
}

type TokenBudgetEntry struct {
	RequestID   string
	BudgetID    int64
	WindowStart int64
	StartedAt   int64
	State       string
	Tokens      int64
	Manual      int64
}
