// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_runtime.sql

package db

import (
	"context"
)

const deleteAccountModelLimit = `-- name: DeleteAccountModelLimit :exec
DELETE FROM account_model_runtime WHERE account_model_runtime.account_id=?1 AND model=?2
 AND version=?3 AND lifecycle=?4 AND runtime_revision=?5
 AND EXISTS(SELECT 1 FROM accounts a LEFT JOIN account_runtime ar ON ar.account_id=a.id
  WHERE a.id=account_model_runtime.account_id AND a.tenant_id=?6
   AND a.models_revision=account_model_runtime.lifecycle AND COALESCE(ar.revision,0)=account_model_runtime.runtime_revision)
`

type DeleteAccountModelLimitParams struct {
	TargetID        string
	Model           string
	Version         int64
	Lifecycle       int64
	RuntimeRevision int64
	WorkspaceID     int64
}

func (q *Queries) DeleteAccountModelLimit(ctx context.Context, arg DeleteAccountModelLimitParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountModelLimit,
		arg.TargetID,
		arg.Model,
		arg.Version,
		arg.Lifecycle,
		arg.RuntimeRevision,
		arg.WorkspaceID,
	)
	return err
}

const deleteAccountModelRuntime = `-- name: DeleteAccountModelRuntime :exec
DELETE FROM account_model_runtime WHERE account_model_runtime.account_id=?1
 AND EXISTS(SELECT 1 FROM accounts a WHERE a.id=account_model_runtime.account_id AND a.tenant_id=?2)
`

type DeleteAccountModelRuntimeParams struct {
	TargetID    string
	WorkspaceID int64
}

func (q *Queries) DeleteAccountModelRuntime(ctx context.Context, arg DeleteAccountModelRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountModelRuntime, arg.TargetID, arg.WorkspaceID)
	return err
}

const deleteObsoleteModelRuntime = `-- name: DeleteObsoleteModelRuntime :exec
DELETE FROM account_model_runtime
WHERE EXISTS(SELECT 1 FROM accounts a LEFT JOIN account_runtime ar ON ar.account_id=a.id
 WHERE a.id=account_model_runtime.account_id AND a.tenant_id=?1
  AND (a.models_revision!=account_model_runtime.lifecycle
   OR COALESCE(ar.revision,0)!=account_model_runtime.runtime_revision
   OR (account_model_runtime.cooldown_until<=?2 AND NOT EXISTS(SELECT 1 FROM json_each(CASE WHEN json_valid(a.models_snapshot) THEN a.models_snapshot ELSE '{}' END,'$.models') j
    WHERE j.value=account_model_runtime.model))))
`

type DeleteObsoleteModelRuntimeParams struct {
	WorkspaceID int64
	Now         int64
}

func (q *Queries) DeleteObsoleteModelRuntime(ctx context.Context, arg DeleteObsoleteModelRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, deleteObsoleteModelRuntime, arg.WorkspaceID, arg.Now)
	return err
}

const getAccountModelRuntime = `-- name: GetAccountModelRuntime :one
SELECT a.models_revision AS lifecycle, COALESCE(ar.revision,0) AS runtime_revision,
       COALESCE(m.cooldown_until,0) AS cooldown_until, COALESCE(m.failures,0) AS failures, COALESCE(m.version,0) AS version
FROM accounts a LEFT JOIN account_runtime ar ON ar.account_id=a.id
LEFT JOIN account_model_runtime m ON m.account_id=a.id AND m.model=?1
 AND m.lifecycle=a.models_revision AND m.runtime_revision=COALESCE(ar.revision,0)
WHERE a.id=?2 AND a.tenant_id=?3
`

type GetAccountModelRuntimeParams struct {
	Model       string
	TargetID    string
	WorkspaceID int64
}

type GetAccountModelRuntimeRow struct {
	Lifecycle       int64
	RuntimeRevision int64
	CooldownUntil   int64
	Failures        int64
	Version         int64
}

func (q *Queries) GetAccountModelRuntime(ctx context.Context, arg GetAccountModelRuntimeParams) (GetAccountModelRuntimeRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountModelRuntime, arg.Model, arg.TargetID, arg.WorkspaceID)
	var i GetAccountModelRuntimeRow
	err := row.Scan(
		&i.Lifecycle,
		&i.RuntimeRevision,
		&i.CooldownUntil,
		&i.Failures,
		&i.Version,
	)
	return i, err
}

const saveAccountModelRuntime = `-- name: SaveAccountModelRuntime :one
INSERT INTO account_model_runtime(account_id,model,cooldown_until,failures,lifecycle,runtime_revision,version)
SELECT a.id,?1,?2,?3,a.models_revision,?4,1
FROM accounts a
WHERE a.id=?5 AND a.tenant_id=?6
 AND a.models_revision=?7
 AND COALESCE((SELECT revision FROM account_runtime WHERE account_runtime.account_id=a.id),0)=?4
ON CONFLICT(account_id,model) DO UPDATE SET cooldown_until=excluded.cooldown_until, failures=excluded.failures,
 lifecycle=excluded.lifecycle,runtime_revision=excluded.runtime_revision,version=account_model_runtime.version+1
RETURNING version
`

type SaveAccountModelRuntimeParams struct {
	Model           string
	CooldownUntil   int64
	Failures        int64
	RuntimeRevision int64
	TargetID        string
	WorkspaceID     int64
	Lifecycle       int64
}

func (q *Queries) SaveAccountModelRuntime(ctx context.Context, arg SaveAccountModelRuntimeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveAccountModelRuntime,
		arg.Model,
		arg.CooldownUntil,
		arg.Failures,
		arg.RuntimeRevision,
		arg.TargetID,
		arg.WorkspaceID,
		arg.Lifecycle,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
