// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID         string
	Provider   string
	Name       string
	AccountID  string
	Email      string
	Plan       string
	Enabled    bool
	Status     string
	Credential []byte
	ExpiresAt  int64
	CreatedAt  int64
	UpdatedAt  int64
}
