// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxies.sql

package db

import (
	"context"
)

const bindAccountProxy = `-- name: BindAccountProxy :execrows
UPDATE accounts SET proxy_id = ?1, updated_at = ?2,
 models_snapshot = NULL, models_revision = models_revision + 1
WHERE id = ?3 AND tenant_id = ?4
`

type BindAccountProxyParams struct {
	ProxyID   *string
	UpdatedAt int64
	ID        string
	TenantID  int64
}

func (q *Queries) BindAccountProxy(ctx context.Context, arg BindAccountProxyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindAccountProxy,
		arg.ProxyID,
		arg.UpdatedAt,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countProxies = `-- name: CountProxies :one
SELECT count(*) FROM proxies WHERE tenant_id = ?1
`

func (q *Queries) CountProxies(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProxies, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProxyAccounts = `-- name: CountProxyAccounts :one
SELECT count(*) FROM accounts WHERE proxy_id = ?1
`

func (q *Queries) CountProxyAccounts(ctx context.Context, proxyID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProxyAccounts, proxyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProxy = `-- name: CreateProxy :execrows
INSERT INTO proxies(id, tenant_id, name, address, created_at, updated_at)
VALUES(?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(tenant_id, name) DO NOTHING
`

type CreateProxyParams struct {
	ID        string
	TenantID  int64
	Name      string
	Address   []byte
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProxy,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFailedProxies = `-- name: DeleteFailedProxies :execrows
DELETE FROM proxies WHERE proxies.tenant_id=?1
AND proxies.checked_at >= ?2 AND proxies.reachable=0 AND proxies.check_error='connection_failed'
AND NOT EXISTS(SELECT 1 FROM accounts WHERE accounts.proxy_id=proxies.id)
`

type DeleteFailedProxiesParams struct {
	TenantID     int64
	CheckedSince int64
}

func (q *Queries) DeleteFailedProxies(ctx context.Context, arg DeleteFailedProxiesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFailedProxies, arg.TenantID, arg.CheckedSince)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProxy = `-- name: DeleteProxy :execrows
DELETE FROM proxies WHERE id = ?1 AND tenant_id = ?2
`

type DeleteProxyParams struct {
	ID       string
	TenantID int64
}

func (q *Queries) DeleteProxy(ctx context.Context, arg DeleteProxyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProxy, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProxy = `-- name: GetProxy :one
SELECT id, tenant_id, name, address, created_at, updated_at, revision, checked_at, reachable, exit_ip, country, region, city, latency_ms, check_error FROM proxies WHERE id = ?1 AND tenant_id = ?2
`

type GetProxyParams struct {
	ID       string
	TenantID int64
}

func (q *Queries) GetProxy(ctx context.Context, arg GetProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, getProxy, arg.ID, arg.TenantID)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.CheckedAt,
		&i.Reachable,
		&i.ExitIp,
		&i.Country,
		&i.Region,
		&i.City,
		&i.LatencyMs,
		&i.CheckError,
	)
	return i, err
}

const invalidateProxyCatalogs = `-- name: InvalidateProxyCatalogs :exec
UPDATE accounts SET models_snapshot = NULL, models_revision = models_revision + 1
WHERE proxy_id = ?1
`

func (q *Queries) InvalidateProxyCatalogs(ctx context.Context, proxyID *string) error {
	_, err := q.db.ExecContext(ctx, invalidateProxyCatalogs, proxyID)
	return err
}

const listProxies = `-- name: ListProxies :many
SELECT p.id, p.name, p.address, p.created_at, p.updated_at, p.checked_at, p.reachable,
 p.exit_ip, p.country, p.region, p.city, p.latency_ms, p.check_error,
 (SELECT count(*) FROM accounts a WHERE a.proxy_id = p.id) AS account_count
FROM proxies p WHERE p.tenant_id = ?1
ORDER BY p.created_at DESC, p.id DESC LIMIT 32
`

type ListProxiesRow struct {
	ID           string
	Name         string
	Address      []byte
	CreatedAt    int64
	UpdatedAt    int64
	CheckedAt    int64
	Reachable    int64
	ExitIp       string
	Country      string
	Region       string
	City         string
	LatencyMs    int64
	CheckError   string
	AccountCount int64
}

func (q *Queries) ListProxies(ctx context.Context, tenantID int64) ([]ListProxiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProxies, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxiesRow{}
	for rows.Next() {
		var i ListProxiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CheckedAt,
			&i.Reachable,
			&i.ExitIp,
			&i.Country,
			&i.Region,
			&i.City,
			&i.LatencyMs,
			&i.CheckError,
			&i.AccountCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProxyCheck = `-- name: SaveProxyCheck :execrows
UPDATE proxies SET checked_at=?1, reachable=?2,
 exit_ip=?3, country=?4, region=?5,
 city=?6, latency_ms=?7, check_error=?8
WHERE id=?9 AND tenant_id=?10 AND revision=?11
`

type SaveProxyCheckParams struct {
	CheckedAt  int64
	Reachable  int64
	ExitIp     string
	Country    string
	Region     string
	City       string
	LatencyMs  int64
	CheckError string
	ID         string
	TenantID   int64
	Revision   int64
}

func (q *Queries) SaveProxyCheck(ctx context.Context, arg SaveProxyCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveProxyCheck,
		arg.CheckedAt,
		arg.Reachable,
		arg.ExitIp,
		arg.Country,
		arg.Region,
		arg.City,
		arg.LatencyMs,
		arg.CheckError,
		arg.ID,
		arg.TenantID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProxy = `-- name: UpdateProxy :execrows
UPDATE proxies SET name = ?1,
 revision = revision + CASE WHEN address != ?2 THEN 1 ELSE 0 END,
 checked_at = CASE WHEN address != ?2 THEN 0 ELSE checked_at END,
 reachable = CASE WHEN address != ?2 THEN 0 ELSE reachable END,
 exit_ip = CASE WHEN address != ?2 THEN '' ELSE exit_ip END,
 country = CASE WHEN address != ?2 THEN '' ELSE country END,
 region = CASE WHEN address != ?2 THEN '' ELSE region END,
 city = CASE WHEN address != ?2 THEN '' ELSE city END,
 latency_ms = CASE WHEN address != ?2 THEN 0 ELSE latency_ms END,
 check_error = CASE WHEN address != ?2 THEN '' ELSE check_error END,
 address = ?2, updated_at = ?3
WHERE id = ?4 AND tenant_id = ?5
`

type UpdateProxyParams struct {
	Name      string
	Address   []byte
	UpdatedAt int64
	ID        string
	TenantID  int64
}

func (q *Queries) UpdateProxy(ctx context.Context, arg UpdateProxyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProxy,
		arg.Name,
		arg.Address,
		arg.UpdatedAt,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
