// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
)

const listRequestCallers = `-- name: ListRequestCallers :many
SELECT r.user_id, r.key_id, COALESCE(u.username,'') AS username, COALESCE(k.name,'') AS key_name
FROM request_records r
LEFT JOIN users u ON u.id=r.user_id
LEFT JOIN api_keys k ON k.id=r.key_id
JOIN account_groups g ON g.id=r.group_id
WHERE g.tenant_id=?1
AND (r.user_id=?2 OR ?2=0) AND r.started_at>=?3
GROUP BY r.user_id,r.key_id ORDER BY username,key_name,r.key_id LIMIT 5000
`

type ListRequestCallersParams struct {
	TenantID int64
	UserID   int64
	Since    int64
}

type ListRequestCallersRow struct {
	UserID   int64
	KeyID    int64
	Username string
	KeyName  string
}

func (q *Queries) ListRequestCallers(ctx context.Context, arg ListRequestCallersParams) ([]ListRequestCallersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestCallers, arg.TenantID, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestCallersRow{}
	for rows.Next() {
		var i ListRequestCallersRow
		if err := rows.Scan(
			&i.UserID,
			&i.KeyID,
			&i.Username,
			&i.KeyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT r.id, r.user_id, r.key_id, r.group_id, r.account_id, r.provider, r.model, r.transport, r.operation, r.started_at, r.duration_ms, r.outcome, r.error_code, r.upstream_status, r.input_tokens, r.output_tokens, r.cached_tokens, r.request_id, r.first_token_ms,COALESCE(u.username,'') AS username,COALESCE(k.name,'') AS key_name,COALESCE(g.name,'') AS group_name,COALESCE(a.name,'') AS account_name
FROM request_records r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN api_keys k ON k.id=r.key_id LEFT JOIN account_groups g ON g.id=r.group_id LEFT JOIN accounts a ON a.id=r.account_id
WHERE g.tenant_id=?1
 AND (r.user_id=?2 OR ?2=0) AND (r.id<?3 OR ?3=0) AND (r.account_id=?4 OR ?4='') AND (r.outcome=?5 OR ?5='') AND r.started_at>=?6
 AND (r.started_at<?7 OR ?7=0)
 AND (r.user_id=?8 OR ?8=0)
 AND (r.key_id=?9 OR ?9=0)
 AND (r.model=?10 OR ?10='')
 AND (r.request_id=?11 OR ?11='')
ORDER BY r.id DESC LIMIT 51
`

type ListRequestsParams struct {
	TenantID  int64
	UserID    int64
	Cursor    int64
	AccountID string
	Outcome   string
	Since     int64
	UntilTime int64
	MemberID  int64
	KeyID     int64
	Model     string
	RequestID string
}

type ListRequestsRow struct {
	ID             int64
	UserID         int64
	KeyID          int64
	GroupID        int64
	AccountID      string
	Provider       string
	Model          string
	Transport      string
	Operation      string
	StartedAt      int64
	DurationMs     int64
	Outcome        string
	ErrorCode      string
	UpstreamStatus *int64
	InputTokens    *int64
	OutputTokens   *int64
	CachedTokens   *int64
	RequestID      string
	FirstTokenMs   *int64
	Username       string
	KeyName        string
	GroupName      string
	AccountName    string
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequests,
		arg.TenantID,
		arg.UserID,
		arg.Cursor,
		arg.AccountID,
		arg.Outcome,
		arg.Since,
		arg.UntilTime,
		arg.MemberID,
		arg.KeyID,
		arg.Model,
		arg.RequestID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsRow{}
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyID,
			&i.GroupID,
			&i.AccountID,
			&i.Provider,
			&i.Model,
			&i.Transport,
			&i.Operation,
			&i.StartedAt,
			&i.DurationMs,
			&i.Outcome,
			&i.ErrorCode,
			&i.UpstreamStatus,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.RequestID,
			&i.FirstTokenMs,
			&i.Username,
			&i.KeyName,
			&i.GroupName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRequests = `-- name: PruneRequests :exec
DELETE FROM request_records WHERE request_records.started_at<?1 OR request_records.id<=(SELECT r.id FROM request_records r ORDER BY r.id DESC LIMIT 1 OFFSET 5000)
`

func (q *Queries) PruneRequests(ctx context.Context, beforeTime int64) error {
	_, err := q.db.ExecContext(ctx, pruneRequests, beforeTime)
	return err
}

const recordRequest = `-- name: RecordRequest :exec
INSERT INTO request_records(user_id,key_id,group_id,account_id,provider,model,transport,operation,started_at,duration_ms,outcome,error_code,upstream_status,input_tokens,output_tokens,cached_tokens,request_id,first_token_ms)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18)
`

type RecordRequestParams struct {
	UserID         int64
	KeyID          int64
	GroupID        int64
	AccountID      string
	Provider       string
	Model          string
	Transport      string
	Operation      string
	StartedAt      int64
	DurationMs     int64
	Outcome        string
	ErrorCode      string
	UpstreamStatus *int64
	InputTokens    *int64
	OutputTokens   *int64
	CachedTokens   *int64
	RequestID      string
	FirstTokenMs   *int64
}

func (q *Queries) RecordRequest(ctx context.Context, arg RecordRequestParams) error {
	_, err := q.db.ExecContext(ctx, recordRequest,
		arg.UserID,
		arg.KeyID,
		arg.GroupID,
		arg.AccountID,
		arg.Provider,
		arg.Model,
		arg.Transport,
		arg.Operation,
		arg.StartedAt,
		arg.DurationMs,
		arg.Outcome,
		arg.ErrorCode,
		arg.UpstreamStatus,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.RequestID,
		arg.FirstTokenMs,
	)
	return err
}
