// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime.sql

package db

import (
	"context"
)

const listAccountRuntime = `-- name: ListAccountRuntime :many
SELECT a.id,a.max_concurrency,COALESCE(r.cooldown_until,0) AS cooldown_until,COALESCE(r.reason,'') AS reason,COALESCE(r.failures,0) AS failures,COALESCE(r.last_failure_at,0) AS last_failure_at,COALESCE(r.revision,0) AS revision
FROM accounts a LEFT JOIN account_runtime r ON r.account_id=a.id WHERE a.tenant_id=?1
`

type ListAccountRuntimeRow struct {
	ID             string
	MaxConcurrency int64
	CooldownUntil  int64
	Reason         string
	Failures       int64
	LastFailureAt  int64
	Revision       int64
}

func (q *Queries) ListAccountRuntime(ctx context.Context, tenantID int64) ([]ListAccountRuntimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountRuntime, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountRuntimeRow{}
	for rows.Next() {
		var i ListAccountRuntimeRow
		if err := rows.Scan(
			&i.ID,
			&i.MaxConcurrency,
			&i.CooldownUntil,
			&i.Reason,
			&i.Failures,
			&i.LastFailureAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAccountRuntime = `-- name: SaveAccountRuntime :exec
INSERT INTO account_runtime(account_id,cooldown_until,reason,failures,last_failure_at,revision)
SELECT id,?1,?2,?3,?4,?5 FROM accounts
WHERE id=?6 AND tenant_id=?7
ON CONFLICT(account_id) DO UPDATE SET cooldown_until=excluded.cooldown_until,reason=excluded.reason,failures=excluded.failures,last_failure_at=excluded.last_failure_at,revision=excluded.revision
`

type SaveAccountRuntimeParams struct {
	CooldownUntil int64
	Reason        string
	Failures      int64
	LastFailureAt int64
	Revision      int64
	AccountID     string
	TenantID      int64
}

func (q *Queries) SaveAccountRuntime(ctx context.Context, arg SaveAccountRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountRuntime,
		arg.CooldownUntil,
		arg.Reason,
		arg.Failures,
		arg.LastFailureAt,
		arg.Revision,
		arg.AccountID,
		arg.TenantID,
	)
	return err
}

const setAccountConcurrency = `-- name: SetAccountConcurrency :execrows
UPDATE accounts SET max_concurrency=?1,updated_at=?2
WHERE id=?3 AND tenant_id=?4
`

type SetAccountConcurrencyParams struct {
	MaxConcurrency int64
	Now            int64
	ID             string
	TenantID       int64
}

func (q *Queries) SetAccountConcurrency(ctx context.Context, arg SetAccountConcurrencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountConcurrency,
		arg.MaxConcurrency,
		arg.Now,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
