// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
)

const countEncryptedKeys = `-- name: CountEncryptedKeys :one
SELECT count(*) FROM api_keys WHERE encrypted_secret IS NOT NULL
`

func (q *Queries) CountEncryptedKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEncryptedKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getKeySecret = `-- name: GetKeySecret :one
SELECT k.id,k.user_id,k.token_hash,k.revoked_at,k.encrypted_secret AS secret
FROM api_keys k JOIN users u ON u.id=k.user_id JOIN account_groups g ON g.id=k.group_id
WHERE k.id=?1 AND k.user_id=?2 AND g.tenant_id=?3 AND u.enabled=1
`

type GetKeySecretParams struct {
	ID       int64
	UserID   int64
	TenantID int64
}

type GetKeySecretRow struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	RevokedAt *int64
	Secret    []byte
}

func (q *Queries) GetKeySecret(ctx context.Context, arg GetKeySecretParams) (GetKeySecretRow, error) {
	row := q.db.QueryRowContext(ctx, getKeySecret, arg.ID, arg.UserID, arg.TenantID)
	var i GetKeySecretRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RevokedAt,
		&i.Secret,
	)
	return i, err
}

const listKeySecrets = `-- name: ListKeySecrets :many
SELECT id,user_id,token_hash,encrypted_secret AS secret FROM api_keys
WHERE encrypted_secret IS NOT NULL AND id>?1 ORDER BY id LIMIT 100
`

type ListKeySecretsRow struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	Secret    []byte
}

func (q *Queries) ListKeySecrets(ctx context.Context, afterID int64) ([]ListKeySecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeySecrets, afterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeySecretsRow{}
	for rows.Next() {
		var i ListKeySecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveKeySecret = `-- name: SaveKeySecret :exec
UPDATE api_keys SET encrypted_secret=?1 WHERE id=?2
`

type SaveKeySecretParams struct {
	Secret []byte
	KeyID  int64
}

func (q *Queries) SaveKeySecret(ctx context.Context, arg SaveKeySecretParams) error {
	_, err := q.db.ExecContext(ctx, saveKeySecret, arg.Secret, arg.KeyID)
	return err
}
