// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package db

import (
	"context"
)

const getSetupAccounts = `-- name: GetSetupAccounts :one
SELECT CAST(COUNT(*) AS INTEGER) AS enabled,
CAST(COALESCE(SUM(CASE WHEN status='ready' THEN 1 ELSE 0 END),0) AS INTEGER) AS verified
FROM accounts WHERE tenant_id=?1 AND enabled=1 AND provider IN ('codex','claude','antigravity','xai','openai')
`

type GetSetupAccountsRow struct {
	Enabled  int64
	Verified int64
}

func (q *Queries) GetSetupAccounts(ctx context.Context, tenantID int64) (GetSetupAccountsRow, error) {
	row := q.db.QueryRowContext(ctx, getSetupAccounts, tenantID)
	var i GetSetupAccountsRow
	err := row.Scan(&i.Enabled, &i.Verified)
	return i, err
}

const getSetupMembership = `-- name: GetSetupMembership :one
SELECT m.first_request_at FROM memberships m JOIN users u ON u.id=m.user_id
JOIN tenants t ON t.id=m.tenant_id
WHERE m.tenant_id=?1 AND m.user_id=?2
AND m.enabled=1 AND u.enabled=1 AND t.status='active'
`

type GetSetupMembershipParams struct {
	TenantID int64
	UserID   int64
}

func (q *Queries) GetSetupMembership(ctx context.Context, arg GetSetupMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSetupMembership, arg.TenantID, arg.UserID)
	var first_request_at int64
	err := row.Scan(&first_request_at)
	return first_request_at, err
}

const recordFirstRequest = `-- name: RecordFirstRequest :exec
UPDATE memberships SET first_request_at=?1
WHERE user_id=?2 AND first_request_at=0
AND tenant_id=(SELECT tenant_id FROM account_groups WHERE id=?3)
`

type RecordFirstRequestParams struct {
	StartedAt int64
	UserID    int64
	GroupID   int64
}

func (q *Queries) RecordFirstRequest(ctx context.Context, arg RecordFirstRequestParams) error {
	_, err := q.db.ExecContext(ctx, recordFirstRequest, arg.StartedAt, arg.UserID, arg.GroupID)
	return err
}
