// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statistics.sql

package db

import (
	"context"
)

const canTrackStatisticsModel = `-- name: CanTrackStatisticsModel :one
SELECT CAST(
 EXISTS(SELECT 1 FROM usage_daily s WHERE s.day=?1 AND s.user_id=?2 AND s.model=?3)
 OR (SELECT COUNT(DISTINCT s.model) FROM usage_daily s WHERE s.day=?1 AND s.user_id=?2 AND s.model!='[other models]')<64
AS INTEGER)
`

type CanTrackStatisticsModelParams struct {
	Day    int64
	UserID int64
	Model  string
}

func (q *Queries) CanTrackStatisticsModel(ctx context.Context, arg CanTrackStatisticsModelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, canTrackStatisticsModel, arg.Day, arg.UserID, arg.Model)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStatisticsCoverage = `-- name: GetStatisticsCoverage :one
SELECT value FROM settings WHERE key='usage.daily.started_at'
`

func (q *Queries) GetStatisticsCoverage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getStatisticsCoverage)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getStatisticsTotals = `-- name: GetStatisticsTotals :one
SELECT CAST(COALESCE(SUM(s.requests),0) AS INTEGER) AS requests,
CAST(COALESCE(SUM(s.completed),0) AS INTEGER) AS completed,
CAST(COALESCE(SUM(s.incomplete),0) AS INTEGER) AS incomplete,
CAST(COALESCE(SUM(s.errors),0) AS INTEGER) AS errors,
CAST(COALESCE(SUM(s.canceled),0) AS INTEGER) AS canceled,
CAST(COALESCE(SUM(s.rejected),0) AS INTEGER) AS rejected,
CAST(COALESCE(SUM(s.duration_ms),0) AS INTEGER) AS duration_ms,
CAST(COALESCE(SUM(s.input_tokens),0) AS INTEGER) AS input_tokens,
CAST(COALESCE(SUM(s.output_tokens),0) AS INTEGER) AS output_tokens,
CAST(COALESCE(SUM(s.cached_tokens),0) AS INTEGER) AS cached_tokens,
CAST(COALESCE(SUM(s.input_reported),0) AS INTEGER) AS input_reported,
CAST(COALESCE(SUM(s.output_reported),0) AS INTEGER) AS output_reported,
CAST(COALESCE(SUM(s.cached_reported),0) AS INTEGER) AS cached_reported
FROM usage_daily s
WHERE s.day>=?1 AND s.day<?2 AND (s.user_id=?3 OR ?3=0)
`

type GetStatisticsTotalsParams struct {
	FromDay int64
	ToDay   int64
	UserID  int64
}

type GetStatisticsTotalsRow struct {
	Requests       int64
	Completed      int64
	Incomplete     int64
	Errors         int64
	Canceled       int64
	Rejected       int64
	DurationMs     int64
	InputTokens    int64
	OutputTokens   int64
	CachedTokens   int64
	InputReported  int64
	OutputReported int64
	CachedReported int64
}

func (q *Queries) GetStatisticsTotals(ctx context.Context, arg GetStatisticsTotalsParams) (GetStatisticsTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getStatisticsTotals, arg.FromDay, arg.ToDay, arg.UserID)
	var i GetStatisticsTotalsRow
	err := row.Scan(
		&i.Requests,
		&i.Completed,
		&i.Incomplete,
		&i.Errors,
		&i.Canceled,
		&i.Rejected,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.InputReported,
		&i.OutputReported,
		&i.CachedReported,
	)
	return i, err
}

const listStatistics = `-- name: ListStatistics :many
SELECT CAST(CASE ?1 WHEN 'day' THEN s.day WHEN 'member' THEN s.user_id WHEN 'group' THEN s.group_id ELSE s.model END AS TEXT) AS bucket,
CAST(COALESCE(CASE ?1 WHEN 'day' THEN '' WHEN 'member' THEN u.username WHEN 'group' THEN g.name ELSE s.model END,'') AS TEXT) AS name,
CAST(COALESCE(SUM(s.requests),0) AS INTEGER) AS requests,
CAST(COALESCE(SUM(s.completed),0) AS INTEGER) AS completed,
CAST(COALESCE(SUM(s.incomplete),0) AS INTEGER) AS incomplete,
CAST(COALESCE(SUM(s.errors),0) AS INTEGER) AS errors,
CAST(COALESCE(SUM(s.canceled),0) AS INTEGER) AS canceled,
CAST(COALESCE(SUM(s.rejected),0) AS INTEGER) AS rejected,
CAST(COALESCE(SUM(s.duration_ms),0) AS INTEGER) AS duration_ms,
CAST(COALESCE(SUM(s.input_tokens),0) AS INTEGER) AS input_tokens,
CAST(COALESCE(SUM(s.output_tokens),0) AS INTEGER) AS output_tokens,
CAST(COALESCE(SUM(s.cached_tokens),0) AS INTEGER) AS cached_tokens,
CAST(COALESCE(SUM(s.input_reported),0) AS INTEGER) AS input_reported,
CAST(COALESCE(SUM(s.output_reported),0) AS INTEGER) AS output_reported,
CAST(COALESCE(SUM(s.cached_reported),0) AS INTEGER) AS cached_reported
FROM usage_daily s LEFT JOIN users u ON u.id=s.user_id LEFT JOIN account_groups g ON g.id=s.group_id
WHERE s.day>=?2 AND s.day<?3 AND (s.user_id=?4 OR ?4=0)
GROUP BY 1,2 ORDER BY requests DESC,bucket ASC LIMIT ?5
`

type ListStatisticsParams struct {
	Dimension string
	FromDay   int64
	ToDay     int64
	UserID    int64
	MaxRows   int64
}

type ListStatisticsRow struct {
	Bucket         string
	Name           string
	Requests       int64
	Completed      int64
	Incomplete     int64
	Errors         int64
	Canceled       int64
	Rejected       int64
	DurationMs     int64
	InputTokens    int64
	OutputTokens   int64
	CachedTokens   int64
	InputReported  int64
	OutputReported int64
	CachedReported int64
}

func (q *Queries) ListStatistics(ctx context.Context, arg ListStatisticsParams) ([]ListStatisticsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStatistics,
		arg.Dimension,
		arg.FromDay,
		arg.ToDay,
		arg.UserID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatisticsRow{}
	for rows.Next() {
		var i ListStatisticsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Name,
			&i.Requests,
			&i.Completed,
			&i.Incomplete,
			&i.Errors,
			&i.Canceled,
			&i.Rejected,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.InputReported,
			&i.OutputReported,
			&i.CachedReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneStatistics = `-- name: PruneStatistics :exec
DELETE FROM usage_daily WHERE day<?1
`

func (q *Queries) PruneStatistics(ctx context.Context, beforeDay int64) error {
	_, err := q.db.ExecContext(ctx, pruneStatistics, beforeDay)
	return err
}

const recordStatistics = `-- name: RecordStatistics :exec
INSERT INTO usage_daily(day,user_id,group_id,provider,model,requests,completed,incomplete,errors,canceled,rejected,duration_ms,input_tokens,output_tokens,cached_tokens,input_reported,output_reported,cached_reported)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18)
ON CONFLICT(day,user_id,group_id,provider,model) DO UPDATE SET
requests=usage_daily.requests+excluded.requests,
completed=usage_daily.completed+excluded.completed,
incomplete=usage_daily.incomplete+excluded.incomplete,
errors=usage_daily.errors+excluded.errors,
canceled=usage_daily.canceled+excluded.canceled,
rejected=usage_daily.rejected+excluded.rejected,
duration_ms=usage_daily.duration_ms+excluded.duration_ms,
input_tokens=usage_daily.input_tokens+excluded.input_tokens,
output_tokens=usage_daily.output_tokens+excluded.output_tokens,
cached_tokens=usage_daily.cached_tokens+excluded.cached_tokens,
input_reported=usage_daily.input_reported+excluded.input_reported,
output_reported=usage_daily.output_reported+excluded.output_reported,
cached_reported=usage_daily.cached_reported+excluded.cached_reported
`

type RecordStatisticsParams struct {
	Day            int64
	UserID         int64
	GroupID        int64
	Provider       string
	Model          string
	Requests       int64
	Completed      int64
	Incomplete     int64
	Errors         int64
	Canceled       int64
	Rejected       int64
	DurationMs     int64
	InputTokens    int64
	OutputTokens   int64
	CachedTokens   int64
	InputReported  int64
	OutputReported int64
	CachedReported int64
}

func (q *Queries) RecordStatistics(ctx context.Context, arg RecordStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, recordStatistics,
		arg.Day,
		arg.UserID,
		arg.GroupID,
		arg.Provider,
		arg.Model,
		arg.Requests,
		arg.Completed,
		arg.Incomplete,
		arg.Errors,
		arg.Canceled,
		arg.Rejected,
		arg.DurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.InputReported,
		arg.OutputReported,
		arg.CachedReported,
	)
	return err
}
