// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
)

const canManageTenant = `-- name: CanManageTenant :one
SELECT EXISTS(SELECT 1 FROM memberships m JOIN tenants t ON t.id=m.tenant_id JOIN users u ON u.id=m.user_id
WHERE m.tenant_id=?1 AND m.user_id=?2
AND m.role IN ('owner','admin') AND m.enabled=1 AND u.enabled=1 AND t.status='active')
`

type CanManageTenantParams struct {
	TenantID int64
	ActorID  int64
}

func (q *Queries) CanManageTenant(ctx context.Context, arg CanManageTenantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canManageTenant, arg.TenantID, arg.ActorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT u.id,u.username,m.role,m.enabled,u.enabled AS user_enabled,m.created_at
FROM memberships m JOIN users u ON u.id=m.user_id
WHERE m.tenant_id=?1 AND m.user_id=?2
`

type GetTenantMemberParams struct {
	TenantID int64
	UserID   int64
}

type GetTenantMemberRow struct {
	ID          int64
	Username    string
	Role        string
	Enabled     int64
	UserEnabled bool
	CreatedAt   int64
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (GetTenantMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i GetTenantMemberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Enabled,
		&i.UserEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT u.id,u.username,m.role,m.enabled,u.enabled AS user_enabled,m.created_at
FROM memberships m JOIN users u ON u.id=m.user_id
WHERE m.tenant_id=?1 AND m.role='member'
AND (u.id<?2 OR ?2=0)
ORDER BY u.id DESC LIMIT 51
`

type ListTenantMembersParams struct {
	TenantID int64
	BeforeID int64
}

type ListTenantMembersRow struct {
	ID          int64
	Username    string
	Role        string
	Enabled     int64
	UserEnabled bool
	CreatedAt   int64
}

func (q *Queries) ListTenantMembers(ctx context.Context, arg ListTenantMembersParams) ([]ListTenantMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantMembers, arg.TenantID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Enabled,
			&i.UserEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantMemberEnabled = `-- name: SetTenantMemberEnabled :execrows
UPDATE memberships SET enabled=?1
WHERE tenant_id=?2 AND user_id=?3 AND role='member'
`

type SetTenantMemberEnabledParams struct {
	Enabled  int64
	TenantID int64
	UserID   int64
}

func (q *Queries) SetTenantMemberEnabled(ctx context.Context, arg SetTenantMemberEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTenantMemberEnabled, arg.Enabled, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
