// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timezone.sql

package db

import (
	"context"
)

const getTimeZone = `-- name: GetTimeZone :one
SELECT value FROM settings WHERE key = 'instance.time_zone'
`

func (q *Queries) GetTimeZone(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTimeZone)
	var value string
	err := row.Scan(&value)
	return value, err
}

const saveTimeZone = `-- name: SaveTimeZone :exec
INSERT INTO settings(key,value) VALUES('instance.time_zone',?1)
ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP
`

func (q *Queries) SaveTimeZone(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, saveTimeZone, value)
	return err
}
