// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
)

const getAccountUsage = `-- name: GetAccountUsage :one
SELECT snapshot, updated_at FROM account_usage WHERE account_id = ?1
`

type GetAccountUsageRow struct {
	Snapshot  []byte
	UpdatedAt int64
}

func (q *Queries) GetAccountUsage(ctx context.Context, accountID string) (GetAccountUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountUsage, accountID)
	var i GetAccountUsageRow
	err := row.Scan(&i.Snapshot, &i.UpdatedAt)
	return i, err
}

const saveAccountUsage = `-- name: SaveAccountUsage :exec
INSERT INTO account_usage(account_id, snapshot, updated_at)
VALUES (?1, ?2, ?3)
ON CONFLICT(account_id) DO UPDATE SET snapshot = excluded.snapshot, updated_at = excluded.updated_at
WHERE excluded.updated_at >= account_usage.updated_at
`

type SaveAccountUsageParams struct {
	AccountID string
	Snapshot  []byte
	UpdatedAt int64
}

func (q *Queries) SaveAccountUsage(ctx context.Context, arg SaveAccountUsageParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountUsage, arg.AccountID, arg.Snapshot, arg.UpdatedAt)
	return err
}
