// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package db

import (
	"context"
)

const getCodexVersionState = `-- name: GetCodexVersionState :one
SELECT value FROM settings WHERE key = 'codex.version'
`

func (q *Queries) GetCodexVersionState(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getCodexVersionState)
	var value string
	err := row.Scan(&value)
	return value, err
}

const saveCodexVersionState = `-- name: SaveCodexVersionState :exec
INSERT INTO settings(key,value) VALUES('codex.version',?1)
ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP
`

func (q *Queries) SaveCodexVersionState(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, saveCodexVersionState, value)
	return err
}
